### PR TITLE
Plugin update for latest version of Rocket League

### PR DESCRIPTION
**Pull request by davidebeatrici**
Added:
- Avatar position
- Avatar front vector
- Avatar top vector (calculated by Mumble using front vector)
- Camera front vector
- Camera top vector

Game Version: 1.18
http://www.rocketleaguegame.com/news/2016/05/patch-notes-v1-18-title-update-6/

### CODE REVIEW

**Comment by mkrautz** [comment]
Can you save the file and add a version without spaces instead of tabs?

They add a lot of noise to the diff.

See
https://github.com/mumble-voip/mumble/pull/2307/files?w=1
vs
https://github.com/mumble-voip/mumble/pull/2307/files?w=0

**Comment by davidebeatrici** [comment]
I think that the problem is of the previous code, that had spaces instead of tabs.
Do I need to replace tabs with spaces?

**Comment by mkrautz** [comment]
No, the old code has tabs.
In this change, you're replacing them with spaces.

**Comment by davidebeatrici** [comment]
Yes, you're right, I didn't know that Qt Creator uses spaces instead of tabs by default.
I fixed it :wink:

**Comment by mkrautz** [comment]
Landed via 3eec33aea62566779163a1e052bbbaad6b4be102.

**Pull request closed without merging**
