### PR TITLE
CI(github-actions): Update Ubuntu runners

### PR DESCRIPTION
**Pull request by davidebeatrici**
This is mostly to take advantage of recent clang-format and compiler.

### CODE REVIEW

**Review by Krzmbrzl — CHANGES_REQUESTED** [review]
I'm against this change. These things should not be tied to a specific OS version as that only makes them prone to become deprecated because we forgot to keep updating these.
Also, neither of these tasks uses clang-format and/or any compiler.

**Comment by davidebeatrici** [comment]
This is also related to #6516, we can't wait until `ubuntu-latest` points to `ubuntu-24.04`...

By the way, check the remaining failures in that PR: those are jobs that build Mumble.

**Comment by Krzmbrzl** [comment]
> By the way, check the remaining failures in that PR: those are jobs that build Mumble.

They don't have anything to do with the images that you are changing here?

> we can't wait until ubuntu-latest points to ubuntu-24.04

We have to support 22.04 anyway so I don't see any reason for a required update.

**Comment by davidebeatrici** [comment]
> They don't have anything to do with the images that you are changing here?

Ah, sorry, I changed the wrong workflow file apparently.

> We have to support 22.04 anyway so I don't see any reason for a required update.

Let's continue in #6516.

**Comment by davidebeatrici** [comment]
Closing as the issue in #6516 is fixed.

As for `clang-format`, see #6543.

**Pull request closed without merging**
