### PR TITLE
Plugin update for latest version of Rocket League

### PR DESCRIPTION
**Pull request by davidebeatrici**
Unknown game update.

### CODE REVIEW

**Comment by mkrautz** [comment]
Landed via eb0a2a0f108bb66881dcbb8a240bb3d9d86b5a0f yesterday.

**Comment by lucasmr** [comment]
The plugin works but left and right are reversed.

**Comment by davidebeatrici** [comment]
Try [this](https://drive.google.com/open?id=0B5IcQp5UPsmFQlJLTFlBUnNTV00) one and let me know if left and right are correct :wink:

**Comment by lucasmr** [comment]
Yes, now it's correct. Thanks.

**Comment by davidebeatrici** [comment]
Thank you for your feedback :wink:
https://github.com/mumble-voip/mumble/pull/2320

**Pull request closed without merging**
