### PR TITLE
DOCS(build_linux): Added build instructions for Debian, w/ related Ubuntu issues

### PR DESCRIPTION
**Pull request by jaggzh**
DOCS(build_linux): Added build instructions for Debian, w/ related Ubuntu issues

Added build instructions for Debian, with notes on changes affecting Ubuntu, and a *workaround* for an Opus bug causing a crash (in the docs, not in code).
https://github.com/mumble-voip/mumble/issues/5302

### Checks

- [X] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Comment by Krzmbrzl** [comment]
Please format your commit message according our commit guidelines (just use what you did for the PR title)

**Comment by jaggzh** [comment]
Did I do it right?

**Comment by Krzmbrzl** [comment]
Yes, except now you have an additional merge commit in your branch. If you want to update your branch, please use a rebase instead of a merge. 

Please remove the merge commit again and also you didn't apply Davide's review suggestion :)

**Comment by jaggzh** [comment]
Okay, had to get help on that one. :)

**Comment by Krzmbrzl** [comment]
Okay, so now the commit formatting is perfect :+1: 

However, you still have the issue in your changes that Davide pointed out. Mind fixing that as well (just amend to your current commit)?

**Comment by Krzmbrzl** [comment]
@jaggzh ?

**Review by Krzmbrzl — APPROVED** [review]
I fixed the outstanding issue myself

**Comment by jaggzh** [comment]
Trying to figure out how.

**Comment by Krzmbrzl** [comment]
Huh? This PR has been merged in May after I fixed the open issues myself.

**Comment by diederikdehaas** [comment]
@jaggzh why did you add ``libxcb-xinerama0`` and not ``libxcb-xinerama0-dev`` to the instructions?

**Pull request merged**
