### PR TITLE
FIX: Set C++ standard to 17

### PR DESCRIPTION
**Pull request by iacore**
I had to set this to make it build, otherwise g++ complains about `std::string_view` being used but not being part of C++14.

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Comment by Krzmbrzl** [comment]
Unfortunately, we can't upgrade to C++17 yet. Not all of our code builds with it on all platforms.

**Comment by iacore** [comment]
> Unfortunately, we can't upgrade to C++17 yet. Not all of our code builds with it on all platforms.

That's the same now isn't it?

**Comment by Krzmbrzl** [comment]
You don't need to adapt anaything as the project is set up to compile?using the C++14 standard.

**Comment by iacore** [comment]
> You don't need to adapt anaything as the project is set up to compile using the C++14 standard.

The problem is exactly that GCC (g++) doesn't let me build the project using C++14. Newer protobuf requires `absl::string_view` requires `std::string_view` (only in C++17).

Here: [compile_log.txt](https://github.com/user-attachments/files/16228245/compile_log.txt)

**Comment by Krzmbrzl** [comment]
The problem is known but vendoring Protobuf is not really an option since we want to upgrade to C++17 anyway (once possible). Until then, specific environments require manual C++ standard overwrite

**Comment by iacore** [comment]
Can you document this in the Linux build .md file somehow?

**Comment by iacore** [comment]
I thought about this, and this issue is caused by abesil disrespecting C++ standard set. abesil is used by protobuf. Are you sure you don't want to use another protobuf library?

**Comment by davidebeatrici** [comment]
Are you aware of a valid alternative?

**Comment by Krzmbrzl** [comment]
There is no way for us to switch away from Protobuf. That would absolutely wreck backwards compatibility. Also, it is working rather well.

**Comment by iacore** [comment]
Understood.

**Comment by Krzmbrzl** [comment]
Using FetchContent might be an idea but distributors will likely not agree with this route at all - they tend to want to use the libraries packaged with a given OS.

**Pull request closed without merging**
