### PR TITLE
BREAK(server): Remove DBus support

### LINKED ISSUE #6548: Murmur 1.5 depends unconditionally to DBus
### Description

Starting from version 1.5 I am unable to build murmur without QtDBus dependency.

### Steps to reproduce

1. Unpack sources
2. `mkdir build ; cd build`
3. `cmake`

### Mumble version

1.5.634

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

### Additional information

Worked before in 1.4 version, first bad commit a4cd707128087e5c39dd72d8ae83cec6d88719d0

### Relevant log output

```shell
-- The C compiler identification is GNU 14.2.1
-- The CXX compiler identification is GNU 14.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python interpreter version 3.12.6
-- Performing Test COMPILER_HAS_MBIG_OBJ
-- Performing Test COMPILER_HAS_MBIG_OBJ - Failed
-- Using (among others) the following compiler flags: -Wall;-Wpedantic;-Wextra;-Wconversion;-Wsign-conversion;-fsigned-char
-- ##################################################
-- Mumble version:              1.5.634
-- Architecture:                x64
-- Build type:                  RelWithDebInfo
-- Using LTO in release builds: ON
-- ##################################################
CMake Warning at CMakeLists.txt:126 (message):
  Use of option "BUILD_TESTING" is deprecated.  Use "tests" instead.


-- Qt5 component found: Core | Version: 5.15.14
-- Qt5 component found: Network | Version: 5.15.14
-- Qt5 component found: Xml | Version: 5.15.14
-- OpenSSL component found: Crypto | Version: 3.3.1
-- OpenSSL component found: SSL | Version: 3.3.1
-- Found ZLIB: /usr/lib64/libz.so (found version "1.3.1")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Protobuf found | Version: 28.0.0
-- TRACY_ENABLE: OFF
-- TRACY_ON_DEMAND: ON
-- TRACY_CALLSTACK: OFF
-- TRACY_NO_CALLSTACK: OFF
-- TRACY_NO_CALLSTACK_INLINES: OFF
-- TRACY_ONLY_LOCALHOST: OFF
-- TRACY_NO_BROADCAST: OFF
-- TRACY_ONLY_IPV4: OFF
-- TRACY_NO_CODE_TRANSFER: OFF
-- TRACY_NO_CONTEXT_SWITCH: OFF
-- TRACY_NO_EXIT: OFF
-- TRACY_NO_SAMPLING: OFF
-- TRACY_NO_VERIFY: OFF
-- TRACY_NO_VSYNC_CAPTURE: OFF
-- TRACY_NO_FRAME_IMAGE: OFF
-- TRACY_NO_SYSTEM_TRACING: OFF
-- TRACY_DELAYED_INIT: OFF
-- TRACY_MANUAL_LIFETIME: OFF
-- TRACY_FIBERS: OFF
-- TRACY_NO_CRASH_HANDLER: OFF
-- TRACY_TIMER_FALLBACK: OFF
-- Disabling warnings for targets: TracyClient
-- Tracy: OFF
-- Microsoft.GSL found | Version: 4.0.0
-- Qt5 component found: Sql | Version: 5.15.14
-- File: /var/tmp/portage/net-voip/murmur-1.5.634/work/mumble-1.5.634_build/src/murmur/murmur_autogen
CMake Error at cmake/pkg-utils.cmake:87 (message):
  Qt5 component not found: DBus
Call Stack (most recent call first):
  src/murmur/CMakeLists.txt:187 (find_pkg)
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Krzmbrzl**
The DBus RPC interface on the server has been deprecated for a while and has also not been maintained for even longer. Therefore, the API has now been removed completely.

Instead, users shall make use of the ZeroC Ice interface as a means to do RPC.

Fixes #6548

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Comment by Krzmbrzl** [comment]
@davidebeatrici @Hartmnt are you both okay with these changes? Also, I think `FEAT` is kinda the wrong commit type, but I can't determine a better one :eyes:

**Comment by Hartmnt** [comment]
> are you both okay with these changes?

Sure, isn't this supposed to be deprecated anyway for years now?

> Also, I think `FEAT` is kinda the wrong commit type, but I can't determine a better one 👀

``BREAK``, ``FEAT``, or ``CHANGE``

I also found these:
https://github.com/mumble-voip/mumble/blob/master/3rdPartyLicenses/dbus_license.txt
https://github.com/mumble-voip/mumble/blob/master/scripts/generate_license_header.py#L60
https://github.com/mumble-voip/mumble/blob/master/auxiliary_files/run_scripts/mumble-server-user-wrapper.in#L44
https://github.com/mumble-voip/mumble/blob/master/.github/actions/install-dependencies/install_ubuntu_static_64bit.sh#L10

**Comment by davidebeatrici** [comment]
> Sure, isn't this supposed to be deprecated anyway for years now?

Yup. When the decision was made we had gRPC as well, but I believe keeping a single RPC mechanism is perfectly fine especially from a maintenance perspective.

**Comment by Krzmbrzl** [comment]
> BREAK, FEAT, or CHANGE

Yeah, I guess this has to be `BREAK` - I kinda didn't want to use it as it would technically imply that we'd have to change the major version number of Mumble, but I guess that's just what it is :eyes: 
The only question then is: Do we change the major version number? That would be required when strictly following semantic versioning guidelines. However, I kinda have the feeling that "Mumble 2.0" will raise expectations in users that we simply don't fulfill :thinking: 

> I believe keeping a single RPC mechanism is perfectly fine especially from a maintenance perspective.

It is sufficient for now. In the future I would like the write something like an abstract RPC interface that can then be used as the base for different RPC implementations but where each RPC backend implementation is just a wrapper for the shared functionality (ideally even auto-generated).

**Comment by Hartmnt** [comment]
> Do we change the major version number?

Nah, we merely break a peripheral function of the software that was deprecated before.

**Comment by davidebeatrici** [comment]
> It is sufficient for now. In the future I would like the write something like an abstract RPC interface that can then be used as the base for different RPC implementations but where each RPC backend implementation is just a wrapper for the shared functionality (ideally even auto-generated).

I strongly agree.

**Pull request merged**
