### PR TITLE
Improve Volume adjust per user

### PR DESCRIPTION
**Pull request by SuperNascher**
An improvement for the "Local Volume Adjustment".

![Screenshot]
(https://files.nascher.org/private/localvolumeadjustment_mumble.png)

Changes to the last pull request:
- increase the volume limits (-60 to 30)
- add a QSpinBox
- add a label with a warning text
- add some more buttons (reset, abort)

It's now possible, to open more than one window/dialog of the "Local Volume Adjustment".
But there is no restriction, that is only one instance for a user active.

![Screenshot2]
(https://files.nascher.org/private/localvolumeadjustment_mumble_bug.png)

### CODE REVIEW

**Comment by mkrautz** [comment]
I'm really not sure why you've renamed the class back to the old, discarded name? Can you elaborate on that?

**Comment by SuperNascher** [comment]
No, there was not a specific reason.
I will change the name back.

**Comment by mkrautz** [comment]
I have made various changes to the PR.

PTAL at https://github.com/mkrautz/mumble/commit/b3de5c6835373afa610e22241609e433939f4793

...if it seems OK to merge for you. :-)

Thanks.

**Comment by SuperNascher** [comment]
It looks good, you can merge it ;-)

**Comment by mkrautz** [comment]
@SuperNascher Can I use your real name for the commit name? What is it?

**Comment by SuperNascher** [comment]
Sorry, I have overlooked the line 40 of UserLocalVolumeDialog.cpp :/

https://github.com/mkrautz/mumble/blob/b3de5c6835373afa610e22241609e433939f4793/src/mumble/UserLocalVolumeDialog.cpp#L40

Can you set the parent from the QWidget to NULL?
If there is a parent, than the dialog will not showing up in the taskbar.

**Comment by mkrautz** [comment]
@SuperNascher PTAL: https://github.com/mkrautz/mumble/tree/nachser-uservol-v2

Also, can I use your real name for the commit name? What is it?

**Comment by SuperNascher** [comment]
@mkrautz You can merge it :+1: 

And yes, Kevin Rohland.

**Comment by mkrautz** [comment]
Thanks!

Landed as bd9bb66603f3a03184405b70207662b8f1914f13.

**Pull request closed without merging**
