### PR TITLE
DOCS(build): Update Ubuntu package names 

### PR DESCRIPTION
**Pull request by kaifkh20**
Fixes https://github.com/mumble-voip/mumble/issues/6204

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Comment by davidebeatrici** [comment]
`qt5-qmake` may be unneeded, if the CMake module doesn't rely on files that are provided by it.

**Comment by kaifkhan1** [comment]
Sorry for the inconvenience.
I might have made this PR in a hurry.

**Comment by Krzmbrzl** [comment]
No worries - it's nothing that can't be fixed :)

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
Thank you for your contribution :+1:

**Pull request merged**
