### PR TITLE
MAINT: Potentially Reduce Docker Container Size

### PR DESCRIPTION
**Pull request by jcgoette**
MAINT: Potentially Reduce Docker Container Size

Add "--no-install-recommends" and "rm -rf /var/lib/apt/lists/*"

### CODE REVIEW

**Review by Krzmbrzl — CHANGES_REQUESTED** [review]
Please have a look at our [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md).

I also think that these commits can be squashed together as they are basically trying to achieve the same goal, don't they?

In that case I would use something like this for the combined commit's header:
```
MAINT: Potentially reduce Docker container size
```

(If you want me to change this for you, just let me know)

**Comment by jcgoette** [comment]
Updated as suggested. Fine with squash. :)

**Comment by Krzmbrzl** [comment]
I actually meant to change the commit's message and not primarily the title & description of the PR :)

But nvm, I'll quickly do it myself :point_up:

**Review by Krzmbrzl — APPROVED** [review]

**Review by davidebeatrici — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
Thank you for your contribution :)

**Pull request merged**
