### PR TITLE
TRANSLATION: Drop outdated translation file references

### PR DESCRIPTION
**Pull request by Kissaki**
Previously, duplicate translation files were removed in three commits:
b208fe09d19573c03a08ee2612c56d5fa0c05017 ca_ES
70091f8feaacd1d34d19f24de2f1812622856b55 el_GR
c0434236f16430e6a71454f8100c479c25c1f358 nb_NO

These files were not removed from the CMakeLists.txt and translations.pri.

### CODE REVIEW

**Comment by Kissaki** [comment]
@davidebeatrici shouldn't the CI build fail with non-existent files being referenced in the CMakeLists.txt file?

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/mumble/blob/68f8cd3f0d4b836698b8e73f6fc8da2f6e48e6c4/src/mumble/CMakeLists.txt#L742-L743

https://github.com/mumble-voip/mumble/blob/68f8cd3f0d4b836698b8e73f6fc8da2f6e48e6c4/cmake/qt-utils.cmake#L29-L53

`qt5_create_translation()` also updates the `.ts` files in addition to compiling them into `.qm` ones.

As a result, if a non-existent `.ts` file is referenced, it is created.

**Comment by Kissaki** [comment]
Test failures seem unrelated!?

```
The following tests FAILED:
Errors while running CTest
	 16 - TestServerResolver (Failed)
Error: Process completed with exit code 8.
```

**Comment by davidebeatrici** [comment]
Indeed.

**Review by davidebeatrici — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
> Test failures seem unrelated!?

Probably due to the short outage of our server infrastructure. I have restarted the failed jobs and now they should pass.

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
@Kissaki in order to resolve the merge conflict you could also create an extra commit deleting the .pri file altogether.

**Comment by Kissaki** [comment]
I'm not familiar with the file.

pri file header says it's autogenerated from the transifex bot, so that's another thing to look at. Also dunno how it previously integrated into the build. Doesn't seem to be referenced now.

I resolved the conflicts as is in this PR, without removing the pri file.

**Pull request merged**
