### PR TITLE
Murmur: allow both bitmasked version and version string when setting 'suggestversion' via RPC.

### PR DESCRIPTION
**Pull request by mkrautz**
This commit changes the logic for setting the 'suggestversion' config
option via RPC to automatically figure out whether the passed-in value
is a bitmasked version or a version string.

If it is a version string, it will convert the version string to the
bitmasked format, which is what is used internally.

Prior to this, 'suggestversion' via RPC only allowed a bitmasked
version. This was confusing users, since the .ini file requires a
a version string.

Fixes mumble-voip/mumble#989

### CODE REVIEW

**Comment by hacst** [comment]
Apart from the comment LGTM. 0 is somewhat of a special case in that impl. but it was before and doesn't make sense to set anyways so I'm fine with that.

**Comment by mkrautz** [comment]
@hacst 

PTAL at v2: https://github.com/mkrautz/mumble/commit/6b8b8281870875114c0b436397ee87535877cc1a

**Comment by mkrautz** [comment]
@hacst 

PTAL at v3: https://github.com/mkrautz/mumble/commit/870f974287fecaf2a92c0a848c253ab9dc43bbb6

**Comment by hacst** [comment]
v3 LGTM.

**Comment by mkrautz** [comment]
Landed as 33f8448d7c85962344ee2c19646500d63cf09b09.

**Pull request closed without merging**
