### PR TITLE
FIX(overlay): Don't stop search in find_odlsym() until DT_GNU_HASH is found

### PR DESCRIPTION
**Pull request by davidebeatrici**
Binaries may contain both `DT_HASH` and `DT_GNU_HASH` tables, for broader compatibility.

The previous code used whatever would be found first, since we perform a linear symbol search anyway.

Turns out there are cases in which `DT_HASH` exists but is empty, effectively superseded by `DT_GNU_HASH`.

This commit changes the overall logic so that `DT_HASH` is only used as fallback and when found first.

### CODE REVIEW

**Comment by davidebeatrici** [comment]
@carlocastoldi Could you check whether this fixes #5852, please?

**Comment by carlocastoldi** [comment]
I'm afraid this didn't solve completely the issues:

```
MumbleOverlay: Mumble overlay library loaded
MumbleOverlay: Found DT_HASH at: 0xf7e3b044
MumbleOverlay: Found DT_GNU_HASH at: 0xf7e391f8
MumbleOverlay: Found DT_STRTAB at: 0xf7e39314
MumbleOverlay: Found DT_SYMTAB at: 0xf7e39244
MumbleOverlay: Using DT_GNU_HASH
MumbleOverlay: Using DT_HASH
MumbleOverlay: Failed to find original address of dlsym().
MumbleOverlay: Request for symbol; name: pthread_create, handle: (nil), odlsym: (nil)
MumbleOverlay: Mumble overlay library loaded
MumbleOverlay: Found DT_HASH at: 0xf7e3b044
MumbleOverlay: Found DT_GNU_HASH at: 0xf7e391f8
MumbleOverlay: Found DT_STRTAB at: 0xf7e39314
MumbleOverlay: Found DT_SYMTAB at: 0xf7e39244
MumbleOverlay: Using DT_GNU_HASH
MumbleOverlay: Using DT_HASH
MumbleOverlay: Failed to find original address of dlsym().
MumbleOverlay: Request for symbol; name: pthread_create, handle: (nil), odlsym: (nil)
MumbleOverlay: Mumble overlay library loaded
MumbleOverlay: Found DT_HASH at: 0xf7e3b044
MumbleOverlay: Found DT_GNU_HASH at: 0xf7e391f8
MumbleOverlay: Found DT_STRTAB at: 0xf7e39314
MumbleOverlay: Found DT_SYMTAB at: 0xf7e39244
MumbleOverlay: Using DT_GNU_HASH
MumbleOverlay: Using DT_HASH
MumbleOverlay: Failed to find original address of dlsym().
MumbleOverlay: Mumble overlay library loaded
MumbleOverlay: Found DT_HASH at: 0xf7e3b044
MumbleOverlay: Found DT_GNU_HASH at: 0xf7e391f8
MumbleOverlay: Found DT_STRTAB at: 0xf7e39314
MumbleOverlay: Found DT_SYMTAB at: 0xf7e39244
MumbleOverlay: Using DT_GNU_HASH
MumbleOverlay: Using DT_HASH
MumbleOverlay: Failed to find original address of dlsym().
MumbleOverlay: Request for symbol; name: LauncherMain, handle: 0xa40e000, odlsym: (nil)
Failed to load the launcher entry proc
```

**Comment by carlocastoldi** [comment]
Could it be due to the [infamous](https://www.youtube.com/watch?v=Uj2z-3qAchA) glibc 2.36 update?

https://bugs.gentoo.org/863863
https://sourceware.org/bugzilla/show_bug.cgi?id=29456

**Comment by davidebeatrici** [comment]
According to the log I was right: `DT_HASH` was being relied on instead of `DT_GNU_HASH` as it appears first in the list.

However, my assumption regarding the symbol not being found was wrong: it's not present in `DT_GNU_HASH` either.

I wonder if on your system `dlsym()` is exported by another library...

**Comment by carlocastoldi** [comment]
if i execute the following command in the directory I link with `LD_LIBRARY_PATH` i get:

```
~/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/Team Fortress 2/bin
❯ ls *.so | xargs -I{} sh -c "nm -D {} | grep dlsym | xargs echo '{} --'" 
bsppack.so -- U dlsym@GLIBC_2.0
bugreporter_filequeue.so -- U dlsym@GLIBC_2.0
bugreporter_public.so -- U dlsym@GLIBC_2.0
datacache.so -- U dlsym@GLIBC_2.0
engine.so -- U dlsym@GLIBC_2.0
filesystem_stdio.so -- U dlsym@GLIBC_2.0
GameUI.so -- U dlsym@GLIBC_2.0
inputsystem.so -- U dlsym@GLIBC_2.0
launcher.so -- U dlsym@GLIBC_2.0
libMiles.so --
libopenvr_api.so -- U dlsym@GLIBC_2.0
libsteam_api.so -- U dlsym@GLIBC_2.0
libsteamnetworkingsockets.so -- U dlsym@GLIBC_2.0
libTelemetryX64.so --
libTelemetryX86.so --
libtier0.so -- U dlsym@GLIBC_2.0
libtogl.so -- U dlsym@GLIBC_2.0
libvstdlib.so -- U dlsym@GLIBC_2.0
materialsystem.so -- U dlsym@GLIBC_2.0
replay.so -- U dlsym@GLIBC_2.0
scenefilecache.so -- U dlsym@GLIBC_2.0
ServerBrowser.so -- U dlsym@GLIBC_2.0
shaderapidx9.so -- U dlsym@GLIBC_2.0
shaderapiempty.so -- U dlsym@GLIBC_2.0
soundemittersystem.so -- U dlsym@GLIBC_2.0
sourcevr.so -- U dlsym@GLIBC_2.0
stdshader_dx9.so -- U dlsym@GLIBC_2.0
studiorender.so -- U dlsym@GLIBC_2.0
vaudio_celt.so -- U dlsym@GLIBC_2.0
vaudio_miles.so -- U dlsym@GLIBC_2.0
vaudio_speex.so -- U dlsym@GLIBC_2.0
vgui2.so -- U dlsym@GLIBC_2.0
vguimatsurface.so -- U dlsym@GLIBC_2.0
video_bink.so -- U dlsym@GLIBC_2.0
video_services.so -- U dlsym@GLIBC_2.0
video_webm.so -- U dlsym@GLIBC_2.0
vphysics.so -- U dlsym@GLIBC_2.0
vtex_dll.so -- U dlsym@GLIBC_2.0
```

**Comment by Krzmbrzl** [comment]
@davidebeatrici what's the status on this?

**Comment by davidebeatrici** [comment]
I have to check the library on Ubuntu 22.04.

**Comment by davidebeatrici** [comment]
> I wonder if on your system `dlsym()` is exported by another library...

Confirmed:

```c
$ readelf -Ws --dyn-syms /lib/x86_64-linux-gnu/libdl.so.2

Symbol table '.dynsym' contains 11 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
     1: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_deregisterTMCloneTable
     2: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __gmon_start__
     3: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_registerTMCloneTable
     4: 0000000000000000     0 FUNC    WEAK   DEFAULT  UND __cxa_finalize@GLIBC_2.2.5 (5)
     5: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  ABS GLIBC_2.3.3
     6: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  ABS GLIBC_2.3.4
     7: 0000000000001100     1 FUNC    GLOBAL DEFAULT   14 __libdl_version_placeholder@GLIBC_2.2.5
     8: 0000000000001100     1 FUNC    GLOBAL DEFAULT   14 __libdl_version_placeholder@GLIBC_2.3.4
     9: 0000000000001100     1 FUNC    GLOBAL DEFAULT   14 __libdl_version_placeholder@GLIBC_2.3.3
    10: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  ABS GLIBC_2.2.5
```

**Comment by Krzmbrzl** [comment]
Closing this as stale

**Pull request closed without merging**
