### PR TITLE
Tabs

### PR DESCRIPTION
**Pull request by frmimue**
Added a tab functionality to the logging area.

Default tab is a channel tab, which handles channel and server messages.
A seperated tab is created for every user.
If a tab is updated or the assigned user leaves the server, this is indicated by a different tab color.
All tabs are movable and user tabs are closable with a rightclick.

Also removed every use of qteLog, to generalize operations on the log properties.
mumble_tabs

### CODE REVIEW

**Comment by Xylemon** [comment]
This patch would be great if merged, it makes chatting in Mumble much more functional in my opinion.

**Comment by mkrautz** [comment]
What's the status, @hacst, @frmimue?

**Comment by hacst** [comment]
Unfortunately the patch makes assumptions about there always being a unique cert hash available for a user. This is not guaranteed by Mumble as we (for strange reasons) support users without a certificate at all. As such it needs to be reworked to consider that. I'm not sure @frmimue is still interested in doing so.

**Comment by mkrautz** [comment]
If @frmimue is not interested, I will remove it from the 1.3.0 milestone.

**Comment by Xylemon** [comment]
A shame really. I hope @frmimue either continues this or someone else does.

**Comment by Drexl** [comment]
Ditto. I'd really like to see this.

If @frmimue <https://github.com/frmimue> is not interested, I will remove
it from the 1.3.0 milestone.

—
Reply to this email directly or view it on GitHub
<https://github.com/mumble-voip/mumble/pull/179#issuecomment-116000908>.

**Comment by 01010101010101010101010101010101** [comment]
Chats must be separated. We live in 2017. user interfaces must be user-friendly. Look at the teamspeak 3 realisation. It simple and great. I really love Mumble, and I hope, that community will get separated usable chats in 1.3.0, like other VoIP products (For example: general chat tab for notifications and global chat, local room chat tab and other tabs for private chates).

**Comment by XeonG** [comment]
Please get tabs in mumble desktop gui.... I'm looking at moving away from teamspeak but the client has tab support for pm's and its just an essential really, especially with discord taking over that already has better chatting capabilities but its cloud crap run by untrustworthy sjws morons.

**Comment by dannycolin** [comment]
> @XeonG run by untrustworthy sjws morons.

I do not think that part of your argumentation was really necessary. Having a crude language even if it isn't toward someone in that thread isn't a good way to ask for something. 

Moreover, a good way to show your support and need for that feature would be by "thumbs up" the original post. Mumble's developers are well aware of that feature but their time is limited so they need to prioritize some issues that are more critical.

Please consider that nex time you post on the thread. 

Have a nice day/evening!

**Comment by davidebeatrici** [comment]
Superseded by #3465.

**Pull request closed without merging**
