### PR TITLE
Improve echo cancellation settings ui

### LINKED ISSUE #4110: Enhance echo cancellation seetings UI
**Context**
AudioInput settings page -> echo cancellation (see #4108 for more details)

**Describe the feature you have in mind**
The option for echo cancellation should

1. Show a tooltip why it currently is disabled (if it is disabled that is)
2. update its enabled-state according to the settings that are put into the settings page right now rather than according to what the settings were when the widget was created

### PR DESCRIPTION
**Pull request by Krzmbrzl**
This PR makes sure that the enablement of the echo cancellation ComboBox in the setting is done correctly (and on-the-fly: No need to press `Apply` for this to work) and if it is disabled, a tooltip will explain why.

Fixes #4110 

Changelog
```
| Improved: Echo cancellation setting in the UI is now much more intuitive in regards to when and why it is disabled
```

### CODE REVIEW

**Comment by davidebeatrici** [comment]
Why not return the string directly instead of storing it in a variable?

**Comment by Krzmbrzl** [comment]
> Why not return the string directly instead of storing it in a variable?

What code part are you talking about? :thinking:

**Comment by davidebeatrici** [comment]
For example:
```cpp
const QString ASIOConfig::name = QLatin1String("ASIOConfig");

const QString &ASIOConfig::getName() const {
	return ASIOConfig::name;
}
```

I would replace it with:
```cpp
const QString &ASIOConfig::getName() const {
	return QLatin1String("ASIOConfig");
}
```

**Comment by Krzmbrzl** [comment]
Yeah you're right. I was thinking that I have to take special care here because I want to return a reference but as I'm using returning a const reference, I should be fine returning a string literal directly...

**Comment by davidebeatrici** [comment]
Sorry, should've been:
```cpp
const QString ASIOConfig::getName() const {
	return QLatin1String("ASIOConfig");
}
```

**Comment by Krzmbrzl** [comment]
Yeah that I didn't do because I don't see the need to copy the names all the time as they are in fact static. Thus I want to allocate them once and the use that instance :point_up:

**Comment by davidebeatrici** [comment]
How many times is `getName()` called effectively?

**Comment by Krzmbrzl** [comment]
Probably not often enough for this to make a difference but I still wanted to do it "the best way". And I don't think it clutters the code in the way I did it :thinking:

**Comment by davidebeatrici** [comment]
The memory usage is minimal anyway.

**Pull request merged**
