### PR TITLE
FIX(client): Reorder info in info window

### PR DESCRIPTION
**Pull request by SeerLite**
Reorder information in the Information window so that what's more relevant
to the user is shown first.

### Checks

- [X] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Comment by davidebeatrici** [comment]
Could you post a screenshot, please?

**Comment by SeerLite** [comment]
Forgot about that, sorry!
image
I'm on a tiling WM so the titlebar/decorations are missing in case there are any. Also ignore the light purple border.

Issue with more info: #4773

**Comment by Krzmbrzl** [comment]
I think this is the wrong approach to tackling this issue. Quoting myself from the discussion in the linked issue:
> Imo it'd be best to create a dedicated UI component for this

This way we can use a proper layout and proper GUI components and don't have to assemble this thing as a HTML string. That'd give us much more flexibility for customizing how this looks (and also facilitates future maintenance).

What this means is that you'd go ahead and create a new UI dialog in Qt Designer, click the necessary components together and then you'd have to write the cpp implementation for that new UI class (basically setting the respective texts).
Then instead of assembling this HTML String, we'd create a new instance of this UI class and show that instead.

**Comment by Krzmbrzl** [comment]
I'll create a draft of what I have in mind and then we can discuss on that :point_up:

**Comment by Krzmbrzl** [comment]
I ended up implementing it from top to bottom in #4891.
Thus this PR is superseded by the linked one.

**Pull request closed without merging**
