### PR TITLE
Move "escape" function to mumble_plugin_utils.h header

### PR DESCRIPTION
**Pull request by davidebeatrici**

### CODE REVIEW

**Comment by mkrautz** [comment]
I think it might make more sense to have it in a separate header.

Maybe `mumble_plugin_utils.h`?

Do you want to do it, or should I?

**Comment by davidebeatrici** [comment]
I agree, I think that it doesn't fit well in `mumble_plugin_win32.h`; I'm going to do it :wink:

Where do I need to include `mumble_plugin_utils.h`? In `mumble_plugin_win32.h` or only in the plugins that need it (bf4, bf4_x86 and gtav)?

**Comment by mkrautz** [comment]
Only in the plugins, please! :)

**Comment by davidebeatrici** [comment]
Done :wink:

**Comment by mkrautz** [comment]
Please ensure the header has include guards.

The file should be structured like this:

    <LICENSE.header>
     
    #ifndef MUMBLE_MUMBLE_PLUGIN_UTILS_H_
    #define MUMBLE_MUMBLE_PLUGIN_UTILS_H_

    <header content>
    
    #endif

**Comment by davidebeatrici** [comment]
I forgot about it, sorry; I added them :wink:

**Comment by mkrautz** [comment]
Landed via d3e1c68b2a31f29ceecac1041d029959c0b5e7a6 yesterday.

**Pull request closed without merging**
