### PR TITLE
Positional Audio support for Rocket League and Left 4 Dead 2 plugin update

### PR DESCRIPTION
**Pull request by davidebeatrici**
No context nor identity support available yet.

Thanks to **@mkrautz** on Mumble IRC Chat for the compile fix (https://github.com/mumble-voip/mumble/pull/2195) and for helping me about memory addresses (pModule).
This probably would not have been possible without his help.
Thanks also to **@hacst**: he tried to troubleshoot my compile problem.

### CODE REVIEW

**Comment by mkrautz** [comment]
Hi @davidebeatrici,

Maybe we should add a version to the plugin as well?

Also, could you please use the new-style license header from https://github.com/mumble-voip/mumble/blob/master/LICENSE.header? All new code we add should use that header.

I might get to this before you, and if so, I can fix it for you before landing...

Thanks!

**Comment by davidebeatrici** [comment]
Hi @mkrautz,

I didn't add the plugin version because I thought it wasn't needed: there will be an update soon and we will see if the offsets will change or not; I decided to add the version to the plugin description anyway, if the offsets will not change I will remove the version :wink:

I replaced the license header with the new one :smile:

**Comment by davidebeatrici** [comment]
I wanted to do another pull request for the Left 4 Dead 2 plugin update, but GitHub automatically put the commit into this. I renamed the title :wink: 

Should I update the license header for this?

**Comment by mkrautz** [comment]
No, this seems fine!

**Comment by davidebeatrici** [comment]
Ok :+1:
I will try to add context support to Rocket League's plugin, it shouldn't be too complicated; next thing to the context will be the identity support, I will certainly need some help :smile:

**Comment by mkrautz** [comment]
Thanks. Landed as 80d03543251936a799778463d19e42d5855e9392 and 8017a01b40975330e6ed8ea01642b6155b79d353.

**Pull request closed without merging**
