### PR TITLE
Installer: Do not delete murmur.ini

### LINKED ISSUE #4090: Windows uninstaller deletes murmur.ini
In order to keep behavior consistent with other apps and avoid information loss, do not delete files with user information unless the user has explicitly checked an option to delete such configuration files, which should be disabled by default.

### PR DESCRIPTION
**Pull request by trudnorx**
Fixes #4090.

### CODE REVIEW

**Comment by trudnorx** [comment]
@Krzmbrzl Can you do it? I don't have Git setup rn, I was using the web interface which doesn't allow that.

**Comment by Krzmbrzl** [comment]
Done :)

**Comment by trudnorx** [comment]
@Krzmbrzl thanks :)

**Comment by trudnorx** [comment]
@Krzmbrzl merge?

**Comment by Krzmbrzl** [comment]
> merge?

Yes-. Just wanted the CI to finish and I went on a walk in the meantime :)

**Pull request merged**
