### PR TITLE
FEAT(script): Prompt user for install directory and clone depth

### PR DESCRIPTION
**Pull request by GeneralUser01**
The directory that vcpkg is cloned and installed to can now be determined via user input, with the user's home directory being the default (when no input is provided). The depth limit that's now usable when cloning can be set via user input as well and has no limit by default. If any user input is invalid then the script stops and throws an error message accordingly.

This enables choosing where to put vcpkg along with the dependencies through running the script instead of by editing it beforehand. Setting the clone depth may be used to troubleshoot network problems cancelling the clone or to somewhat reduce the time and storage space required.

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Comment by Krzmbrzl** [comment]
We have a dedicated vcpkg fork by now that essentially deprecate the vcpkg scripts in this repo. 

See github.com/mumble-voip/vcpkg

**Comment by Krzmbrzl** [comment]
We have a dedicated vcpkg fork by now that essentially deprecate the vcpkg scripts in this repo. 

See github.com/mumble-voip/vcpkg

**Comment by davidebeatrici** [comment]
We should probably remove them, to prevent confusion. They're already outdated, anyway.

**Comment by Krzmbrzl** [comment]
@davidebeatrici #6588 

@GeneralUser01 thanks for the PR anyway. I guess you could transform your script enhancements into extra documentation that can be put into the README of https://github.com/mumble-voip/vcpkg. Mind creating a PR there?

**Comment by GeneralUser01** [comment]
Okay, now that the build instructions are being updated accordingly this works. Sure, I'll create a PR in Mumble's vcpkg fork that adds info to the README instead.

**Pull request closed without merging**
