### PR TITLE
travis-ci: switch to Xenial for Qt 5 builds, improve matrix, update MXE mirror

### PR DESCRIPTION
**Pull request by davidebeatrici**
Ubuntu Xenial is available on Travis CI since November: https://blog.travis-ci.com/2018-11-08-xenial-release

Regarding MXE's APT repository: mxe/mxe/issues/2253

### CODE REVIEW

**Comment by Kissaki** [comment]
To me this looks like three different changes, only one of which I feel comfortable having an opinion of on the spot, so I’m delaying any action I could take here right now.

**Comment by davidebeatrici** [comment]
No problem.

**Comment by davidebeatrici** [comment]
macOS build failing because of #3617.

**Comment by davidebeatrici** [comment]
Fixed.

**Comment by davidebeatrici** [comment]
I created a dedicated pull request for the compilation fix: #3626

**Comment by davidebeatrici** [comment]
#3626 has been merged.

**Pull request merged**
