### PR TITLE
Update links to HTTPS

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by davidebeatrici** [comment]
Could write explanatory messages for the commits, please?

**Comment by TotalCaesar659** [comment]
Fixed in https://github.com/mumble-voip/mumble/pull/3922.

**Comment by davidebeatrici** [comment]
There was no need to create a new pull request.

**Comment by davidebeatrici** [comment]
Thank you very much for your contribution!

**Pull request merged**
