### PR TITLE
Update CHANGES.

### PR DESCRIPTION
**Pull request by mkrautz**
Sync it up with our latest changes, and use
people's new names/nyms from .mailmap.

### CODE REVIEW

**Comment by hacst** [comment]
I can't mark it directly in the source as github barfs due to the diff size but I noticed we now have double << >>'s around some names:
```
$git diff HEAD~ | /bin/grep \<\<
+  Tuck Therebelos <<snares@users.sourceforge.net>>
+  kissaki <<kissaki@users.sourceforge.net>>
+  kissaki <<kissaki@users.sourceforge.net>>
+  Bartek "stranded" Sumowski <<sumowski@gmail.com>>
+  theblackstorm <<theblackstorm@users.sourceforge.net>>
+  haru_arc <<arcenciel@users.sf.net>>
+  lewellyn <<lewellyn@users.sourceforge.net>>
+  Tuck Therebelos <<snares@users.sourceforge.net>>
+  haru_arc <<arcenciel@users.sf.net>>
+  kissaki <<kissaki@users.sourceforge.net>>
+  gmc_holle <<gmc_holle@users.sourceforge.net>>
+  ueber <<ueber@users.sourceforge.net>>
+  kissaki <<kissaki@users.sourceforge.net>>
+  dd0t <<dd0t@users.sourceforge.net>>
+  theblackstorm <<theblackstorm@users.sourceforge.net>>
+  kissaki <<kissaki@users.sourceforge.net>>
+  theblackstorm <<theblackstorm@users.sourceforge.net>>
+  Matthias Vogelgesang <<matthias.vogelgesang@gmail.com>>
+  Bartek "stranded" Sumowski <<sumowski@gmail.com>>
+  julian7 <<julian7@users.sourceforge.net>>
+  Bartek "stranded" Sumowski <<sumowski@gmail.com>>
+  dd0t <<dd0t@users.sourceforge.net>>
+  dd0t <<dd0t@users.sourceforge.net>>
+  jerhum <<jerhum@users.sourceforge.net>>
+  Matthias Vogelgesang <<matthias.vogelgesang@gmail.com>>
+  Bartek "stranded" Sumowski <<sumowski@gmail.com>>
+  ikasamah <<ikasamah@users.sourceforge.net>>
+  Bartek "stranded" Sumowski <<sumowski@gmail.com>>
+  dd0t <<dd0t@users.sourceforge.net>>
+  mokomull <<mokomull@users.sourceforge.net>>
+  Mikkel Krautz <<mikkel@krautz.dk>>
+  dd0t <<dd0t@users.sourceforge.net>>
+  Bartek "stranded" Sumowski <<sumowski@gmail.com>>
+  dd0t <<dd0t@users.sourceforge.net>>
+  dd0t <<dd0t@users.sourceforge.net>>
+  mystic_sam <<mystic_sam@users.sourceforge.net>>
+  dd0t <<dd0t@users.sourceforge.net>>
+  dd0t <<dd0t@users.sourceforge.net>>
+  entitaet <<entitaet@users.sourceforge.net>>
+  jakobdettner <<jakobdettner@users.sourceforge.net>>
+  l-n <<l-n@users.sourceforge.net>>
+  Bartek "stranded" Sumowski <<sumowski@gmail.com>>
+  derandi <<derandi@users.sourceforge.net>>
+  Matthias Vogelgesang <<matthias.vogelgesang@gmail.com>>
+  jerhum <<jerhum@users.sourceforge.net>>
+  ikasamah <<ikasamah@users.sourceforge.net>>
+  Bartek "stranded" Sumowski <<sumowski@gmail.com>>
+  derandi <<derandi@users.sourceforge.net>>
+  prosper_spurius <<prosper_spurius@users.sourceforge.net>>
+  prosper_spurius <<prosper_spurius@users.sourceforge.net>>
+  prosper_spurius <<prosper_spurius@users.sourceforge.net>>
+  Matthias Vogelgesang <<matthias.vogelgesang@gmail.com>>
+  derandi <<derandi@users.sourceforge.net>>
+  inequation <<inequation@users.sourceforge.net>>
+  derandi <<derandi@users.sourceforge.net>>
+  derandi <<derandi@users.sourceforge.net>>
+  mark7 <<mark7@users.sourceforge.net>>
+  Mikkel Krautz <<mikkel@krautz.dk>>
+  Mikkel Krautz <<mikkel@krautz.dk>>
+  arrai <<array.of.intellect@gmail.com>>
+  Mikkel Krautz <<mikkel@krautz.dk>>
+  derandi <<derandi@users.sourceforge.net>>
+  Mikkel Krautz <<mikkel@krautz.dk>>
+  dark-storm <<dark-storm@users.sourceforge.net>>
+  l-n <<l-n@users.sourceforge.net>>
+  Mikkel Krautz <<mikkel@krautz.dk>>
+  jerhum <<jerhum@users.sourceforge.net>>
+  Mikkel Krautz <<mikkel@krautz.dk>>
+  Mikkel Krautz <<mikkel@krautz.dk>>
+  vader42 <<vader42@users.sourceforge.net>>
+  Mikkel Krautz <<mikkel@krautz.dk>>
+  mit_service <<mit_service@users.sourceforge.net>>
+  Mikkel Krautz <<mikkel@krautz.dk>>
+  ikasamah <<ikasamah@users.sourceforge.net>>
+  Mikkel Krautz <<mikkel@krautz.dk>>
+  Mikkel Krautz <<mikkel@krautz.dk>>
+  ars3niy <<ars3niy@users.sourceforge.net>>
+  metz <<metz@users.sourceforge.net>>
+  fitti_01 <<fitti_01@users.sourceforge.net>>
+  fitti_01 <<fitti_01@users.sourceforge.net>>
+  fitti_01 <<fitti_01@users.sourceforge.net>>
+  vegars <<vegars@users.sourceforge.net>>
+  dersebi <<dersebi@users.sourceforge.net>>
+  naproxeno <<naproxeno@users.sourceforge.net>>
```
Looks like mostly but not exclusively legacy sf ones and not for all entries either. Something in the legacy handling?

**Comment by mkrautz** [comment]
@hacst Fix at https://github.com/mumble-voip/mumble/pull/2270

**Comment by mkrautz** [comment]
PTAL. Re-ran with the fix.

**Comment by mkrautz** [comment]
Seems broken, still... Hold on.

**Comment by mkrautz** [comment]
OK. Seemingly forgot to add the changed file.

PTAL.

**Comment by hacst** [comment]
Oops. We are using the wrong time field from git here. E.g. the grpc commits are strewn all over the changelog since 2015. Since the changelog is meant to represent what changed in _mumble_ the time stuff landed in master seems more appropriate. I think using the CommitDate instead of the AuthorDate should give the correct result.

**Comment by mkrautz** [comment]
Not a regression.

**Comment by hacst** [comment]
You agree that it's not good for changelog though? If so I'm fine with it being a new issue and landing it as is for now.

**Comment by mkrautz** [comment]
I agree that it would make very much sense for CHANGES to follow the same ordering that "git log" uses by default.

**Comment by mkrautz** [comment]
Landed via abb770b66c159bedaa2bba51ffd16657cbfe8caa

**Pull request closed without merging**
