### PR TITLE
Timer: use clock_gettime with CLOCK_MONOTONIC if available.

### PR DESCRIPTION
**Pull request by mkrautz**
Fixes mumble-voip/mumble#1065

### CODE REVIEW

**Comment by hacst** [comment]
Could we use boost chrono (and later std::chrono) to get rid of all the preprocessor stuff? ```boost::chrono::steady_clock``` should have the properties we want.

**Comment by mkrautz** [comment]
Or QElapsedTimer, which is mostly a drop-in replacement for Timer.

**Comment by hacst** [comment]
Or that ;) From the documentation it seems to use the same time sources. Are we requiring >=Qt 4.7 for the server by now? https://wiki.mumble.info/wiki/FAQ#What_platforms_does_it_run_on.3F is a bit imprecise.

**Comment by mkrautz** [comment]
For 1.3.x, we require the very latest 4.8 release for Qt 4.

**Comment by hacst** [comment]
I thought that was a client thing and we were more lenient for the server. But you know much better what we require w.r.t to legacy so totally fine with me.

**Comment by mkrautz** [comment]
I think your suggestion of `boost::chrono` is more sane for now, in that we wouldn't have to change a lot of the existing users of `Timer`. I briefly looked into implementing `::now()` using `boost::chrono` but quickly realized it would be much easier if we could use `auto`. I'll see if I can get it into a prettier state than where it is right now...

**Pull request closed without merging**
