### PR TITLE
Backport "BUILD(client): RNNoise: Support linking against the system library"

### PR DESCRIPTION
**Pull request by felixsinger**
### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Comment by felixsinger** [comment]
Tested on NixOS. Mumble is linked against the system library.

**Comment by klemensn** [comment]
I was already wondering how and when the OpenBSD related changes (incl. this one) would make it into the `1.4.x` branch, especially now that 1.4.230 was cut without them.

Is there documentation about release branches and the backport/merge process from master into them?

**Comment by Krzmbrzl** [comment]
No documentation but the idea is rather straight forward: As soon as a release branch has been created, no new features will be merged into it. But all bug fixes that can be backported (with reasonable effort) will be - unless we forget one

**Comment by felixsinger** [comment]
Do you consider this patch as a bug fix?

**Comment by hax404** [comment]
I would consider this patch as bug fix, because linux distributions might want to use system libraries. It also doesn't change the default behavior of the build process.

**Comment by klemensn** [comment]
> No documentation but the idea is rather straight forward: As soon as a release branch has been created, no new features will be merged into it. But all bug fixes that can be backported (with reasonable effort) will be - unless we forget one

Despite the `BUILD` nature of my commits, they all either unbreak the build on OpenBSD (#5416, #5417) and/or restore functionality lost in the switch from qmake to cmake (#5422).

Thus I'd consider them build **fixes**.

**Comment by Krzmbrzl** [comment]
No I don't consider this a bug fix, which is why I wouldn't have backported it on my own but now that you have created the backport PR anyway, I'll of course merge it into the 1.4 branch (after all it is definitely not a new feature which would be a no go in terms of backports).

Note: This PR has not been merged yet because I did not get to do it. Since the release of 1.4 my GitHub inbox completely exploded and I don't have the time to process everything during the week.

**Comment by klemensn** [comment]
> No I don't consider this a bug fix, which is why I wouldn't have backported it on my own but now that you have created the backport PR anyway, I'll of course merge it into the 1.4 branch (after all it is definitely not a new feature which would be a no go in terms of backports).

Alright, I'll just cherry-pick the fixes until 1.5.x is branched/released.

> Note: This PR has not been merged yet because I did not get to do it yet. Since the release of 1.4 my GitHub inbox completely exploded and I don't have the time to process everything during the week.

No worries, thanks for your time and work!

**Comment by felixsinger** [comment]
Thanks a lot!

**Comment by felixsinger** [comment]
ping :)

**Pull request merged**
