### PR TITLE
DOCS: Add FindPythonInterpreter error to common build errors

### PR DESCRIPTION
**Pull request by wabash1**
TYPE(Scope): DOCS

Found this extremely helpful and I had difficulty finding this error.
https://githubmemory.com/repo/mumble-voip/mumble/issues/5120

Adds a line to FAQ for updating submodules

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Review by Krzmbrzl — CHANGES_REQUESTED** [review]
Thanks for fixing this!

Could you please rephrase your commit message (not the title or description of this PR but the actual message of your git commit) to use the TYPE `DOCS`? E.g.
```
DOCS: Add FindPythonInterpreter error to common build errors
```

In order to do that, use the following steps
1. Navigate into your clone of the repo and checkout your patch-branch
2. `git commit --amend`
3. Edit the commit message and save&quit your editor of choice
4. `git push -f` (this force-pushes your branch on GitHub to update this PR with your local changes)

**Comment by Krzmbrzl** [comment]
> not the title or description of this PR but the actual message of your git commit

:point_up: 

You only changed the PR title - the commit is still unchanged. Are you perhaps unfamiliar with git as such? In that case I could reword the commit message for you...

**Comment by wabash1** [comment]
> > not the title or description of this PR but the actual message of your git commit
> 
> ☝️
> 
> You only changed the PR title - the commit is still unchanged. Are you perhaps unfamiliar with git as such? In that case I could reword the commit message for you...

First commit and I was doing it from the website, sorry.

**Comment by Krzmbrzl** [comment]
Alright, no worries. I'll fix it up for you.

For reference: In order to change the commit's message you'll have to clone the repo locally and work with the git program itself (either via CLI or some GUI). Aka: it's not possible on GitHub

**Comment by wabash1** [comment]
Good to know Thank you!

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
Thanks for improving the docs :+1:

**Pull request merged**
