### PR TITLE
BUILD(cmake): Increase OSX deployment target

### PR DESCRIPTION
**Pull request by Krzmbrzl**
According to https://doc.qt.io/qt-5/macos.html#supported-versions Qt5
itself only supports macOS down to version 10.13. Given that our project
is completely Qt-based, it does not make sense to target a lower version
of macOS than that.

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Review by davidebeatrici — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
It seems like the overlay is using a deprecated API. @davidebeatrici do you happen to know what we could use instead?

**Comment by davidebeatrici** [comment]
```cpp
/Users/runner/work/1/s/src/mumble/Overlay.cpp:54:4: error: 'CFPropertyListCreateFromXMLData' is deprecated: first deprecated in macOS 10.10 - Use CFPropertyListCreateWithData instead. [-Werror,-Wdeprecated-declarations]
                        CFPropertyListCreateFromXMLData(nullptr, data, kCFPropertyListImmutable, nullptr));
                        ^
/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:41:19: note: 'CFPropertyListCreateFromXMLData' has been explicitly marked deprecated here
CFPropertyListRef CFPropertyListCreateFromXMLData(CFAllocatorRef allocator, CFDataRef xmlData, CFOptionFlags mutabilityOption, CFStringRef *errorString) API_DEPRECATED("Use CFPropertyListCreateWithData instead.", macos(10.0,10.10), ios(2.0,8.0), watchos(2.0,2.0), tvos(9.0,9.0));
                  ^
In file included from src/mumble/CMakeFiles/mumble.dir/Unity/unity_2_cxx.cxx:29:
/Users/runner/work/1/s/src/mumble/Overlay.cpp:90:8: error: 'LSFindApplicationForInfo' is deprecated: first deprecated in macOS 10.10 - Use LSCopyApplicationURLsForBundleIdentifier instead. [-Werror,-Wdeprecated-declarations]
        err = LSFindApplicationForInfo(kLSUnknownCreator, bundleId, nullptr, nullptr, &bundleUrl);
              ^
/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LSInfoDeprecated.h:765:1: note: 'LSFindApplicationForInfo' has been explicitly marked deprecated here
LSFindApplicationForInfo(
^
```

**Comment by Krzmbrzl** [comment]
> Use CFPropertyListCreateWithData

Oh yeah lol. It seems that I tend to not scroll to read the complete error message xD

**Review by Kissaki — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
@davidebeatrici could you test the changes I made or simply overtake updating the code for me? I have no clue what I am doing there and I also have absolutely no way of testing what the code ends up doing. That's quite a bad combination xD

**Comment by davidebeatrici** [comment]
I'm no expert either, but the code looks good to me.

@TerryGeng Do you perhaps have any games installed you can test this PR with?

**Comment by TerryGeng** [comment]
@davidebeatrici I'm sorry that I never succeed in making Overlay work... Mac's safeguard always stops me from testing. Perhaps I should disable the annoying SIP in the end.

**Comment by Krzmbrzl** [comment]
@davidebeatrici will you take care of this PR? My changes don't compile but developing against the CI is just extremely cumbersome...

**Comment by davidebeatrici** [comment]
Don't forget about https://github.com/mumble-voip/mumble/blob/9d5feb54e650148b2da65e1d3db282bf6872ed6f/macx/scripts/osxdist.py#L289-L293.

**Review by Krzmbrzl — COMMENTED** [review]
Code changes LGTM (though that doesn't have to mean much as I have 0% knowledge of macOS stuff xD)

The first commit should have type `REFAC` though as it doesn't actually fix anything, does it?
And from a formal point of view I think the first commit could be split in two parts: One dealing with the deprecated constructs and the other with refactoring the code. But I guess that is not really important here :shrug: 

EDIT: I can't approve this PR as it was originally created by me but consider this to be my approval once the commit type has been changed.

**Review by Krzmbrzl — COMMENTED** [review]
_Approved_

**Comment by Krzmbrzl** [comment]
@davidebeatrici I take it this is now ready to be merged?

**Pull request merged**
