### PR TITLE
DOCS(docker): Document Docker Compose '--build' switch.

### PR DESCRIPTION
**Pull request by pataquets**
### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Comment by pataquets** [comment]
Aside from that commit, wouldn't it be better to set the Docker Compose `restart` policy to `unless-stopped` instead of `always`? ([docs](https://docs.docker.com/config/containers/start-containers-automatically/))

**Comment by Krzmbrzl** [comment]
`unless-stopped` sounds reasonable, yes

**Review by Krzmbrzl — APPROVED** [review]

**Comment by pataquets** [comment]
I'll send it in another PR once this is in. I've messed up a bit my fork's branches :worried:

**Comment by pataquets** [comment]
Sent #5437.

**Pull request merged**
