### PR TITLE
GlobalShortcutWin: delay winhook initialization until after our first timeTicked() slot.

### PR DESCRIPTION
**Pull request by mkrautz**
This removes any observable mouse lag from the winhook initialization
process.

Fixes mumble-voip/mumble#2273

### CODE REVIEW

**Comment by mkrautz** [comment]
PTAL @hacst @Kissaki @fwaggle @Natenom

**Comment by ElPumpo** [comment]
Nice

**Comment by hacst** [comment]
LGTM. Do we need error handling on this? Doesn't look like it can end up in a horrible state but who knows...

**Comment by mkrautz** [comment]
Depends on what the Unhook* functions accept.

If the thread's exec() method returns early, before it has run a timeTicked() slot, hhKeyboard and hhMouse will be NULL.

If Unhook* doesn't like NULL inputs, we could end up in a bad state.

I'll add some `if`s to those...

**Pull request merged**
