### PR TITLE
installer: remove non-static installer logic.

### PR DESCRIPTION
**Pull request by mkrautz**
This is to aid in making the installer WiX project
a bit more maintainable and readable.

If we need the old non-static installer, we always
have the history in Git.

### CODE REVIEW

**Comment by mkrautz** [comment]
I think this should go in, but I'd like to see how people feel about this.

**Comment by Kissaki** [comment]
Simplifying is always good.
As we have static as the default, and the static devenv works fine, I agree this should be dropped.
(If I understand this correctly anyway.)

**Comment by hacst** [comment]
Yeah. Let's drop it. No use in pretending we care to maintain it now.

**Comment by mkrautz** [comment]
Landed 9222b9afe32d55153ddfbcfed23205a83614196f.

**Pull request closed without merging**
