### PR TITLE
MAINT(vcpkg): Install Qt's MySQL and PostgreSQL plugins

### LINKED ISSUE #5450: ServerDB: Database driver QMYSQL not available
### Description

Hello,
When I install Mumble server 1.4.230 to update my 1.3.4 installation, I don't have the choice of the installation path.
Moreover, when I try to start the server, I receive the message :
ServerDB: Database driver QMYSQL not available

While the latter works perfectly with version 1.3.4.

### Steps to reproduce

1. Have a mumble server running under windows
2. Use QMYSQL driver
3. Try to install mumble server 1.4.230
4. Can't choose the install path, so copy files to the right install folder
5. Try to start the server

### Mumble version

1.4.230

### Mumble component

Server

### OS

Windows

### Reproducible?

Yes

### Additional information

_No response_

### Relevant log output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by davidebeatrici**
Fixes #5450.

### CODE REVIEW

**Comment by Krzmbrzl** [comment]
Why do we need to explicitly include the MySQL plugin but not the ones for SQLite or PostgreSQL?

**Comment by davidebeatrici** [comment]
The SQLite plugin is enabled by default, the PostgreSQL isn't. Should we install it as well?

**Comment by Krzmbrzl** [comment]
If we're enabling MySQL, then I think we should also enable PostgreSQL to stay consistent. That way we'll include plugins for all supported DB backends

**Comment by davidebeatrici** [comment]
Sounds good, should I do it in this PR?

**Review by Krzmbrzl — APPROVED** [review]

**Pull request merged**
