### PR TITLE
ConnectDialog: enable "Edit" button's AutoDefault property

### PR DESCRIPTION
**Pull request by davidebeatrici**
Requested in #3410.

### CODE REVIEW

**Comment by hacst** [comment]
Wouldn't we have to auto-default all the buttons to get the desired behaviour?

**Comment by davidebeatrici** [comment]
It was requested only for the **Edit** button.

**Comment by Kissaki** [comment]
Can your commits and PRs _please_ be self contained and explanatory?  The commit should explain _why_ it is changed/set this way.

**Comment by Kissaki** [comment]
So I hate to have this discussion all over the place, but this doesn't seem to make sense. All buttons should behave the same.

I can already use ALT+E to open the edit dialog. This seems to be about being able to use ENTER (which is my guess because you did not even share your intent here), but why should that only be enabled for a single button??

**Comment by Krzmbrzl** [comment]
I just verified that Alt+E does trigger the edit button. Therefore I think this PR is unneeded.

If you think differently, let me know, but for now I'll close it...

**Pull request closed without merging**
