### PR TITLE
TRANSLATION: Remove empty translations

### PR DESCRIPTION
**Pull request by Kissaki**
These were requested and approved at some point in Transifex.
However, no work was ever done on translating to them.

With the imminent move to another translation platform,
we take this opportunity to prune empty translations from it.

These translations can be added upon request again, just like any other.
But they served no value as empty, dead translation files with no progress.

### CODE REVIEW

**Comment by davidebeatrici** [comment]
`translation.pri` was only used by qmake, we can delete it.

**Review by davidebeatrici — APPROVED** [review]

**Comment by Kissaki** [comment]
Test failures seem unrelated!?

```
The following tests FAILED:
Errors while running CTest
	 16 - TestServerResolver (Failed)
Error: Process completed with exit code 8.
```

**Comment by davidebeatrici** [comment]
Indeed.

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
> translation.pri was only used by qmake, we can delete it.

The only question would be: Do we want to do that in this PR or do we want a separate PR for that?

**Comment by davidebeatrici** [comment]
Separate PR.

**Pull request merged**
