### PR TITLE
Add Developer Console to Mumble

### PR DESCRIPTION
**Pull request by mkrautz**

### CODE REVIEW

**Comment by dstensnes** [comment]
Broken? For me fails to build because of line 11 in src/mumble/DeveloperConsole.cpp:
  m_window->clear();

Function is undefined apparently. Running Debian 8.

**Comment by mkrautz** [comment]
We should be able to remove that line to fix the Qt 4 build.

**Comment by dstensnes** [comment]
I replaced it with
```
m_window->clearFocus();
m_window->close();
```

but not sure if that is needed, as I have very little experience with qt. It has been running fine all day though, even though I have opened that window a couple of times. So, I am totally not helpful here....

**Comment by mkrautz** [comment]
Fixed in the tree, thanks!

**Pull request merged**
