### PR TITLE
FIX(client, ui): remove gaps within chat

### LINKED ISSUE #5886: Gap appears above each line of text
### Description

1.4.287 addresses the text scaling issue but introduces a gap above each line of text

Relevant: https://github.com/mumble-voip/mumble/pull/5866

### Steps to reproduce

1. Look at the text pane

### Mumble version

1.4.287

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Additional information

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by bkaestner**
This commit removes the additional gaps within the chat. The gaps were introduced by Qt's block-padding between frames. With this commit, the block *after* the last chat message is set to invisible.

The previous approach of a very small `fontPoinzSize()` within the `blockCharFormat()` unfortunately didn't work on Windows. This variant should work on both Windows and Linux; unfortunately, I was only able to test it on Windows.

Fixes #5886.

### Comparison
Before the patch (on 78350de057a75c062e2cc314cf2df675517712e6):

grafik

After the patch:

grafik

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Comment by bkaestner** [comment]
I just noticed that there is still the initial first block leftover; I could probably hide that one within `LogTextBrowser::LogTextBrowser`, but that would split the "hide the block" logic across two files. Or one could hide it in the initial `Log::processDeferredLogs` call.

**Comment by Krzmbrzl** [comment]
I think hiding the first block in a separate file should be no problem. After all, the required logic is not super complex and it also does not involve a lot of code. :shrug:

**Comment by bkaestner** [comment]
Want me to add that to this PR as well? I'd amend the commit then.

**Comment by Krzmbrzl** [comment]
Yes, please go ahead :+1:

**Comment by Krzmbrzl** [comment]
Meanwhile, I can confirm that this also works on Linux.

**Comment by bkaestner** [comment]
> Meanwhile, I can confirm that this also works on Linux.

That's good to know, thanks for verifying!

> Yes, please go ahead 👍

Currently not at my developer station, so it might take some hours till I can add the change. With that in mind I'd like to use that time to get back to the actual place of the logic: I personally would prefer to hide the initial block either in `Log::processDeferredLogs` or` Log::Log`, but it could also be done within `LogTextBrowser::LogTextBrowser`. I'm not too familiar with Mumble's source code structure, to be honest, and would like for you to decide the actual place :)

**Comment by Krzmbrzl** [comment]
`Log::processDeferredLogs` is not a good place as this does not have anything to do with processing deferred logs. I think the best place would probably be `Log::Log` as I think one could consider this step as part of the log's initialization and thus the ctor seems a fitting candidate.

I'm hesitant to put it in the LogTextBrowser itself, as perhaps we might someday end up using that class for something else as well and perhaps we prefer to have a different logic in that separate place.

**Comment by bkaestner** [comment]
> I think the best place would probably be `Log::Log`

Done, thanks for the recommendation and quick guidance.

By the way: the failing check on the latest commit is a spurious [18.04 brownout since Ubuntu 18.04 is deprecated within GitHub actions](https://github.com/actions/runner-images/issues/6002). You may want to remove that one from [`.github/workflows/build.yml`](https://github.com/mumble-voip/mumble/blob/master/.github/workflows/build.yml) and instead add 22.04 :)

**Comment by Krzmbrzl** [comment]
Thanks for fixing this :+1: 

> By the way: the failing check on the latest commit is a spurious https://github.com/actions/runner-images/issues/6002. You may want to remove that one from [.github/workflows/build.yml](https://github.com/mumble-voip/mumble/blob/master/.github/workflows/build.yml?rgh-link-date=2022-10-14T12%3A39%3A46Z) and instead add 22.04 :)

#5928 :)

**Comment by Krzmbrzl** [comment]
Side-note: It seems that this fix as introduced a regression on the selection behavior in the chat log. See #6045

**Pull request merged**
