### PR TITLE
Update portfile.cmake

### PR DESCRIPTION
**Pull request by dextercai**
MAINT: Update hash in Ice port file (vcpkg)

### CODE REVIEW

**Comment by Krzmbrzl** [comment]
We have successfully used this configuration in the past and I am not aware of any changes that were made to our Ice fork. So I am wondering: What problem did you have with this? :thinking:

**Comment by davidebeatrici** [comment]
mumble-voip/ice@a9d68a8d1d884b839f871c46b4ea94b3fc6d6527 was pushed.

**Comment by Krzmbrzl** [comment]
Ah okay :bulb:

**Review by Krzmbrzl — CHANGES_REQUESTED** [review]
Please make sure that your commit follows our [commit guidlines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md?rgh-link-date=2021-04-05T18%3A52%3A56Z).

For this change I propose
```
MAINT: Update hash in Ice port file (vcpkg)
```

**Comment by dextercai** [comment]
> Please make sure that your commit follows our [commit guidlines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md?rgh-link-date=2021-04-05T18%3A52%3A56Z).
> 
> For this change I propose
> 
> ```
> MAINT: Update hash in Ice port file (vcpkg)
> ```

edited.

**Comment by davidebeatrici** [comment]
Did you perhaps forgot to push?

**Review by dextercai — COMMENTED** [review]
MAINT: Update hash in Ice port file (vcpkg)

Closes #4911

**Comment by dextercai** [comment]
see commit cf17204f322024b508279b6ac531208d9fdde667

**Comment by dextercai** [comment]
done @Krzmbrzl

**Comment by Krzmbrzl** [comment]
Why is the commit body the same as the title though?
If there is nothing separate to say (as I think is the case here) you can just leave away the commit body and make it only be the title :point_up:

**Comment by Kissaki** [comment]
I’d appreciate if the commit or PR description/MR commit provided that context, that a commit was pushed and it needs to be updated because of that.

The fact that it was asked is a clear indicator that it should be mentioned/documented. (Preferably not just in a reply comment down within this PR.)

**Comment by dextercai** [comment]
So what should I do next? Push another commit?

**Comment by davidebeatrici** [comment]
Force-push, like you did the first time.

**Comment by dextercai** [comment]
finished

**Comment by Krzmbrzl** [comment]
I took the liberty of adding the description that Kissaki mentioned :)

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
@dextercai why did you delete the branch? This change was not merged yet

**Comment by Krzmbrzl** [comment]
Now we can't merge it anymore

**Comment by Krzmbrzl** [comment]
I still had the commit locally on my machine and created #4919 from it.

**Comment by dextercai** [comment]
sorry for my wrong operation

**Comment by Krzmbrzl** [comment]
Yeah well it wasn't too bad since I still had the commit locally on my machine :shrug: 

Thanks for fixing this though :+1:

**Pull request closed without merging**
