### PR TITLE
Optional start menu shortcut for installer

### LINKED ISSUE #4083: Windows installer forces start menu item
Windows installer should not be forcing the user to create a start menu item but offering it as an option like most other programs.

### PR DESCRIPTION
**Pull request by trudnorx**
Fixes #4083. Not checked to be working.

### CODE REVIEW

**Comment by Krzmbrzl** [comment]
From the CI:
```
D:\a\1\s\installer\Product.wxs(148): error LGHT0102: The localization variable !(loc.MUMBLE_SEC_StartMenuShortcut) is unknown.  Please ensure the variable is defined. [D:\a\1\s\installer\MumbleInstall.wixproj]
D:\a\1\s\installer\Product.wxs(148): error LGHT0102: The localization variable !(loc.DESC_StartMenuShortcut) is unknown.  Please ensure the variable is defined. [D:\a\1\s\installer\MumbleInstall.wixproj]
D:\a\1\s\installer\Product.wxs(172): error LGHT0102: The localization variable !(loc.MUMBLE_SEC_StartMenuShortcut) is unknown.  Please ensure the variable is defined. [D:\a\1\s\installer\MumbleInstall.wixproj]
D:\a\1\s\installer\Product.wxs(172): error LGHT0102: The localization variable !(loc.DESC_StartMenuShortcut) is unknown.  Please ensure the variable is defined. [D:\a\1\s\installer\MumbleInstall.wixproj]
Done Building Project "D:\a\1\s\installer\MumbleInstall.wixproj" (default targets) -- FAILED.
Done Building Project "D:\a\1\s\installer\MumbleInstall.sln" (Clean;Build target(s)) -- FAILED.

Build FAILED.
```

**Comment by Krzmbrzl** [comment]
Note that you can easily check whether your changes are working once the Windows CI has run successfully: Just follow the link to AzurePipelines and go to `Published artifacts`. From there you can download the WindowsInstaller it has built.

**Comment by trudnorx** [comment]
Just means that the new entry I added to English.wxs has to be propagated to the other languages... anyone can do that with a script or something?

**Comment by Krzmbrzl** [comment]
I don't think we have a script for that. At least I can't find one :eyes:

**Comment by Krzmbrzl** [comment]
@trudnorx could you please verify that this patch works as expected by downloading the built installer?

https://dev.azure.com/Mumble-VoIP/Mumble/_build/results?buildId=1537&view=artifacts&type=publishedArtifacts

**Comment by trudnorx** [comment]
@Krzmbrzl Thank you for doing the language thing.
Right now the only VM I have is Windows 32 bit, is there a 32 bit link?

**Comment by Krzmbrzl** [comment]
Uhm I don't think so xD

I thought you had a normal windows machine available - which is why I asked you first. If you only have VM though, I can boot my windows machine and try it there :)

**Comment by trudnorx** [comment]
@Krzmbrzl You can either do that or I will make a Win7 x64 VM when I can if you want.

**Comment by Krzmbrzl** [comment]
I already tested it. It works :+1_

**Pull request merged**
