### PR TITLE
add stale bot

### PR DESCRIPTION
**Pull request by reelsense**
I've noticed there has been extra effort to cleanup old issues (**594, wow**) in the repo. I suggest adding a **_Stale bot_** to the Mumble repo. I'm guessing by the response to my [GH Issue](https://github.com/mumble-voip/mumble/issues/3273) you guys are busy, _or_ not interested. I'm ready to find out which it is _(Just trying to help)_.

1. Install/auth to GitHub Org: https://probot.github.io/apps/stale/

In 30 days you will find out real fast which issues are still being responded to and which you want to mark as pinned. Worst case, an issue gets closed; just sort by `label:stale` and reopen.

Check out the other "apps" to automate requesting info or enforcing standards.

https://probot.github.io/apps/

I use these on over 60 repositories. Stale bot is my favorite(It's simple and always works). Let me know if you have any questions.

---
x-post: https://github.com/mumble-voip/mumble/issues/3273

### CODE REVIEW

**Comment by reelsense** [comment]
I would have added your additional labels but I'm not sure if the `/` will escape them and make the bot fail so I left it all defaults.

```
priority/P0 - Blocker
priority/P1 - Critical
priority/P2 - Important
priority/P3 - Somewhat important
priority/P4 - Low
priority/P5 - Not important
```

**Comment by davidebeatrici** [comment]
Hi, thank you very much for your help.

I immediately read the issue when you created it, but I wanted to hear the other team members before responding.
Unfortunately that never happened, because most of the team is busy and we are rarely able to chat all together.

We're very sorry for that.

In my opinion, it would definitely help us to organize the issues and I don't see any reasons for not accepting the idea.

@mkrautz Any opinions?

**Comment by Kissaki** [comment]
I’m split…

It’s a sad state either way - long standing open tickets or too early closed tickets.
There's definitely a need to manage tickets, and an incentive to close closable ones, and fix fixable ones, but I’m not sure automated handling will save us work. Will it lead to more labeling and management being necessary?

We have a needs-input label. I guess an answer could remove the label, and no answer over x time could close the ticket as stale.

**Comment by mkrautz** [comment]
I agree with @Kissaki.

FWIW, back on SourceForge, their issue tracker would auto-close after 30 days of inactivity (or maybe it was 14 days?)

As Kissaki suggets, we could apply that to issues that has the needs-input label.

**Comment by reelsense** [comment]
github-pr-review_required

**Pull request closed without merging**
