### PR TITLE
compiler.pri: pass '-compress 9' to rcc.

### PR DESCRIPTION
**Pull request by mkrautz**

### CODE REVIEW

**Comment by mkrautz** [comment]
Drops qrc_mumble_flags.cpp from 39MB (!!!) to 14MB.

**Comment by mkrautz** [comment]
Allows me to build on VMs with low memory (512MB) on both Debian and OpenBSD.

**Comment by hacst** [comment]
Sounds great. LGTM. Any gain in setting ```threshold``` too?

**Comment by mkrautz** [comment]
I believe the default is OK. We can always tweak the compression/threshold later if they cause any problems. The most important thing for me, is that we reduce the memory footprint required to compile Mumble 1.3.0 significantly...

**Comment by mkrautz** [comment]
Landed as 0c08e7300cdeae4520465149f1b6c77de15622eb.

**Pull request closed without merging**
