### PR TITLE
Recompress png files and ico files

### PR DESCRIPTION
**Pull request by ibmibmibm**

### CODE REVIEW

**Comment by mkrautz** [comment]
Sorry for taking long to get to this.

It's hard to take action when there is no visible gain here on the GitHub PR. Would have been nice with some stats. :)

**Comment by ibmibmibm** [comment]
```
icons/config_asio.png          | Bin 8609 -> 6823 bytes
 icons/config_audio_input.png   | Bin 13017 -> 10306 bytes
 icons/config_audio_output.png  | Bin 13017 -> 10306 bytes
 icons/config_basic.png         | Bin 13017 -> 10306 bytes
 icons/config_lcd.png           | Bin 2683 -> 2049 bytes
 icons/config_msgs.png          | Bin 12492 -> 10070 bytes
 icons/config_network.png       | Bin 12492 -> 10070 bytes
 icons/config_osd.png           | Bin 8357 -> 7051 bytes
 icons/config_plugin.png        | Bin 16065 -> 11940 bytes
 icons/config_shortcuts.png     | Bin 11926 -> 7669 bytes
 icons/config_ui.png            | Bin 13497 -> 11544 bytes
 icons/mumble.ico               | Bin 410598 -> 154900 bytes
 icons/mumble.osx.installer.png | Bin 92384 -> 55895 bytes
 icons/mumble.osx.png           | Bin 16554 -> 9138 bytes
 icons/murmur.16x16.png         | Bin 428 -> 267 bytes
 icons/murmur.32x32.png         | Bin 522 -> 325 bytes
 icons/murmur.48x48.png         | Bin 616 -> 386 bytes
 icons/murmur.64x64.png         | Bin 702 -> 355 bytes
 18 files changed, 0 insertions(+), 0 deletions(-)
```

**Comment by mkrautz** [comment]
Note to self: we should check how many of the UI PNG files are actually still used. I think we've mostly moved all of the UI icons to PNG, so perhaps many of them can be dropped, instead of adding a new revision to Git.

**Comment by mkrautz** [comment]
From a cursory glance, *Config.cpp seem to use the PNGs for their icons.
Thanks for the PR, merging...

**Pull request merged**
