### PR TITLE
Pull request for issue #3857

### PR DESCRIPTION
**Pull request by Aleks118**
Included 'Update server access tokens', in to the message. Which will make it clear for the (potentially new) user, that they need to update the tokens in order to potentially get access to the server. This is the first pull request of two. Im making this initial pull request to make sure this get put in the program, incase my second request doesn't get merged.

### CODE REVIEW

**Comment by davidebeatrici** [comment]
Shouldn't we specify that the password is wrong instead?

@Krzmbrzl

**Comment by Krzmbrzl** [comment]
That would make it obvious for most user from the "outside". And I think people knowing that Mumble uses server access tokens will probably also know that this is the equivalent of a password.
Thus I think it might be a good idea to talk about a wrong/missing password, yeah :+1:

**Comment by Krzmbrzl** [comment]
Just for actually cross-referenceing the respective issue: #3857

**Comment by Krzmbrzl** [comment]
This PR got superseded by #3929

**Pull request closed without merging**
