### PR TITLE
MAINT: Update copyright notice to 2021 (Part III)

### PR DESCRIPTION
**Pull request by Kissaki**
The first[1] and second[2] commits did not include all files.

[1] 59ae429972c16c377135bcccfee646b7df446933
[2] 56db3410c536aa42265eac871ffdf4d266862f54

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Comment by Krzmbrzl** [comment]
What is that file even? It seems as if this should be removed and be generated from the regular license file as needed...

**Comment by Kissaki** [comment]
It is embedded into the installer. The installer shows the copyright notice until 2020.

**Comment by Kissaki** [comment]
Looks like the macOS build usually builds in 12 mins, but here it failed with a timeout after 1 hour twice??

**Comment by Kissaki** [comment]
Feel free to implement a better concept. For now, this is a fixup for the installer which shows the wrong, outdated date.

**Comment by Kissaki** [comment]
GitHub shows the file as binary by default. Note that rtf is a text format though, and you can use view file to show it just fine.

**Comment by Krzmbrzl** [comment]
> Looks like the Azure macOS build usually builds in 12 mins, but here it failed with a timeout after 1 hour twice??

Yeah sometimes it has issues with downloading the env. No idea what is going on there :shrug:

**Comment by Kissaki** [comment]
Looks like it succeeded now.

So what’s your thoughts on approving or disapproving this PR?

**Review by Krzmbrzl — APPROVED** [review]
I can't see the actual changes but the PR title seems promising :D

**Pull request merged**
