### PR TITLE
WIP: ALSA recovery PR + fixes

### PR DESCRIPTION
**Pull request by mkrautz**

### CODE REVIEW

**Comment by Eriner** [comment]
@mkrautz if it's of any help, I experience the same symptoms as the user from #2179 which has not been resolved by merging this patch set onto HEAD when building from git. FWIW, I've been experiencing this issue for about a year. Mumble is the only application that has this issue, and I'm running an ALSA-only stack. Let me know if there's any worthwhile info I can provide.

**Comment by Eriner** [comment]
As mentioned in #2179, explicitly setting the period_size and buffer_size to the values mumble uses has seemingly resolved that issue for me. Perhaps some calls to `snd_pcm_hw_params_set_buffer_size` & `snd_pcm_hw_params_set_periods` could be used to resolve this issue without requiring the user to manually change their ALSA configuration?

**Comment by mkrautz** [comment]
@Eriner That's pretty much what we do: https://github.com/mumble-voip/mumble/blob/master/src/mumble/ALSAAudio.cpp#L435-L445

Also, I'm pretty sure what we got back from the ALSA calls was pretty much the values you put in your asoundrc.

Perhaps the period and buffer sizes you set in the asoundrc are the ones that dmix use when opening the hw device. I guess it's possible there wasn't enough buffering to match Mumble's frame size - but re-configuring dmix to use multiples of Mumble's frame size meant that no buffering was necessary (1-to-1 mapping between the two layers).

Most programs won't have problems, because latency is not a priority.

**Comment by Eriner** [comment]
@mkrautz thanks for the links to source, that makes sense. Perhaps provide a warning in STDERR if the hwparams aren't multiples of mumble's frame size? Basically, I think we need some way of signaling to the user that they should futz with their settings (as I did) to resolve the issue, if that is indeed the solution.

**Comment by mkrautz** [comment]
@Eriner But in your case, they *were* multiples of the Mumble frame size, IIRC... I wonder if we can query the hw device's params. Maybe we need some special-cases for that (find the hw device for a given dmix device)... Needs some investigation.

**Comment by Eriner** [comment]
@mkrautz you are correct about my testing multiples of mumble's frame size, hmm.

**Comment by Krzmbrzl** [comment]
Closing this as discontinued for now

**Pull request closed without merging**
