### PR TITLE
FIX(positional-audio): Update Source Engine plugin to work with L4D2 2.2.1.3

### PR DESCRIPTION
**Pull request by davidebeatrici**
This pull request makes the plugin work again with the Linux version of the game.

The game update didn't break support for the Windows version.

https://steamcommunity.com/games/L4D2/announcements/detail/4625740823862061052

### CODE REVIEW

**Review by Krzmbrzl — APPROVED** [review]
:shrug:

**Comment by davidebeatrici** [comment]
Please note that #5125 is also required, in case we want to backport this.

**Comment by Krzmbrzl** [comment]
Idk - do we want to? I guess it's a fix after all, so that would mean that we do, right? :thinking:

**Comment by davidebeatrici** [comment]
We probably should.

**Comment by Krzmbrzl** [comment]
Okay then go ahead and create the backport PR :+1:

**Pull request merged**
