### PR TITLE
MAINT(docs): move and improve global shortcuts instructions and explanation

### PR DESCRIPTION
**Pull request by davidebeatrici**

### CODE REVIEW

**Review by Krzmbrzl — COMMENTED** [review]
Imo this should be a separate documentation file. The Readme is not the correct place to bundle all user-information.
We can however link to the new doc-file from the Readme.

I would put the shortcut docs into the `docs` directory

**Comment by davidebeatrici** [comment]
I agree.

Does `GlobalShortcuts.md` sound good? Also, should it be in `docs` or in `docs/additional-readmes`?

**Comment by Krzmbrzl** [comment]
Yeah sounds good to me.

Just put it into `docs`. I will probably restructure that directory when adding the compile instructions anyways, so I think it doesn't matter all that nuch anyways :)

**Review by Krzmbrzl — APPROVED** [review]
We could also link the new documentation from the readme

**Comment by davidebeatrici** [comment]
I think we should link the directory instead, otherwise we would have to add several links.

**Comment by Krzmbrzl** [comment]
That's fine as well

**Pull request merged**
