### PR TITLE
MAINT: Add Code of Conduct

### PR DESCRIPTION
**Pull request by davidebeatrici**
https://nocodeofconduct.com

### CODE REVIEW

**Comment by davidebeatrici** [comment]
I think it goes straight to the point, why do you think it's very unprofessional?

**Comment by Kissaki** [comment]
I find the tone of that is pissy, and dismissive of efforts to shape inclusive or positive communities.

If would definitely not want to interact or accept certain kinds of discussionrs or pull requests. I think “we accept anyone’s contributions” is a dangerous claim.

I think the linked website misses the point of CoCs.

That website proceeds to say that for physical stuff is “understandably different” but fails to establish why. It does not make sense to me.

I would rather not have any CoC document than this awful thing.

**Comment by Kissaki** [comment]
Generally, I do think a CoC is a good idea though. So I would rather have a (good) CoC over nothing. But this is absolutely not it.

**Comment by Kissaki** [comment]
With that kind of tone I also think the file itself should explain itself. Otherwise it’s an instant selector for people to leave.

**Comment by davidebeatrici** [comment]
> I find the tone of that is pissy, and dismissive of efforts to shape inclusive or positive communities.

It's dismissive of the dangerous and fake attempts to shape inclusive or positive communities.

> If would definitely not want to interact or accept certain kinds of discussionrs or pull requests. I think “we accept anyone’s contributions” is a dangerous claim.

“we accept anyone’s contributions” does not mean that we accept all contributions, it simply means that we do not care who the author is.

> I think the linked website misses the point of CoCs.
>
> That website proceeds to say that for physical stuff is “understandably different” but fails to establish why. It does not make sense to me.
>
> I would rather not have any CoC document than this awful thing.
>
> With that kind of tone I also think the file itself should explain itself. Otherwise it’s an instant selector for people to leave.

I'm pretty sure a lot of people are familiar with the threats that appeared in the last few years in the open-source world. More specifically, the file refers to the CoC(s) that many projects adopted.

Contamination and infiltration by REALLY dangerous people is not a conspiracy, in fact it's happening as we speak.

> Generally, I do think a CoC is a good idea though. So I would rather have a (good) CoC over nothing. But this is absolutely not it.

We can write our own, if you wish.

**Comment by ZeroAbility** [comment]
I think trying to predict how someone may react to how things are worded is unrealistic. Do I think a CoC makes sense as a core concept? Not really, but I also don't think we can make assumptions that random people will treat others the way they would like to be treated any more than we can guess how they would react to the wording. I think we need a common sense and simply defined set of expectations everyone can adhere to without needing to make assumptions or require information about what that person is. It should be enough that they have or want to obtain the skills to help the project grow, have a concept of common courtesy and mutual respect, and can take constructive criticism without equating that to some kind of personal attack. If this PR doesn't get merged and we don't decide to put something in writing, maybe this discussion will be something we can refer to if people have concerns about expectations.

**Comment by Krzmbrzl** [comment]
Well how about something like this then?
```
# Contributor Code of Conduct

We expect everyone participating in the development and/or discussions related to the Mumble project to use a friendly tone, regardless of whom the conversation partner might be.

We explicitly state that we do not care about (nor do we accept discrimination based on) things like (including but not limited to) gender, country of origin, skin color and/or skill sets.

Additionally we expect everyone to be able to voice and receive objective criticism.
```

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Kissaki** [comment]
> > I find the tone of that is pissy, and dismissive of efforts to shape inclusive or positive communities.
> 
> It's dismissive of the dangerous and fake attempts to shape inclusive or positive communities.

Well I do not agree. And if you think differently clearly it’s not unambiguous and providing some intention description and reasoning would have helped the discussion when proposing this, instead of what it was.

**Comment by Kissaki** [comment]
> I'm pretty sure a lot of people are familiar with the threats that appeared in the last few years in the open-source world. More specifically, the file refers to the CoC(s) that many projects adopted.
> 
> Contamination and infiltration by REALLY dangerous people is not a conspiracy, in fact it's happening as we speak.

Well, I don’t know what you are referring to, and if you don’t provide that context you can make assumptions all you want, but those you communicate with will not have the same understanding of neither the situation nor the discussion.

**Review by Kissaki — APPROVED** [review]

**Comment by davidebeatrici** [comment]
@Kissaki I can see why you think differently without the context.

**Pull request merged**
