### PR TITLE
 murmur_grpc: check if an environment variable is set and don't use "which" on Windows

### PR DESCRIPTION
**Pull request by davidebeatrici**

### CODE REVIEW

**Comment by bontibon** [comment]
The --plugin flag isn't a requirement for protoc.  It is only used for additional search directories outside of PATH when looking for the plugin executable.

We should probably just drop the --plugin flag entirely and expect that grpc_cpp_plugin be in one of the PATH directories.

**Comment by davidebeatrici** [comment]
Done.

**Comment by davidebeatrici** [comment]
It breaks the build, let me restore the original changes.

**Comment by davidebeatrici** [comment]
Indeed.

I originally tested it with MSYS2 and it worked fine.

**Pull request merged**
