### PR TITLE
WIP: Build Murmur with gRPC support by default

### LINKED ISSUE #3429: Build Murmur with gRPC by default
Hello!

I saw that Murmur now has support for gRPC instead of Ice for communications as of #1196. However, it doesn't look like the publicly build image has support for that built in. Would it be possible for gRPC to be enabled when building Murmur on all platforms? I am testing from a Mac and would love to not have to compile mumble and murmur manually.

Thanks!

---

# Status

* [ ] There seem to be segfaults/crashes in some cases - to be documented ([[1]](https://github.com/mumble-voip/mumble/pull/3947#issue-365020608), [[2]](https://github.com/mumble-voip/mumble/issues/2569#issuecomment-629134572))
* [ ] Our gRPC implementation [does not yet seem to provide all that Ice does](https://github.com/mumble-voip/mumble/issues/3429#issuecomment-505453643)

### PR DESCRIPTION
**Pull request by davidebeatrici**
Fixes #3429.

### CODE REVIEW

**Comment by bontibon** [comment]
Build error: https://travis-ci.org/mumble-voip/mumble/jobs/406083765

**Comment by Kissaki** [comment]
The commits that disable grpc building should specify why this is necessary.

I don't see why our builds in azure and or travis should not build grpc support. Especially when we build it in releases. The whole point of those jobs is so they verify stuff (that we build and ship) is still buildable.

**Comment by Kissaki** [comment]
It’s worth pointing out that this changes the dependency from protobuf version 2 to protobuf version 3. This is a breaking, non-backwards compatible change and should be prominently labeled as such in the commit, PR description and merge commit.

**Comment by Kissaki** [comment]
What is murmur_grpcwrapper_protoc_plugin?

**Comment by Kissaki** [comment]
What makes our grpc stuff require Qt5 with no Qt4 support?

**Comment by Krzmbrzl** [comment]
This PR is no longer applicable. And given the current status of the gRPC implementation this wouldn't be a good idea anyways (for now)

**Pull request closed without merging**
