### PR TITLE
ignore connecting users in qhUsers hash in gRPC implementation

### LINKED ISSUE #3299: Segfault during UserQuery gRPC call
I have no idea what causes it nor how to reproduce it.
```
(gdb) bt
#0  0x00000000004a67fa in ToRPC(Server const*, User const*, MurmurRPC::User*) ()
#1  0x00000000004bc0b3 in MurmurRPC::Wrapper::V1_UserQuery::impl(bool) ()
#2  0x0000000000439bfa in ExecEvent::execute() ()
#3  0x00000000004a762c in MurmurRPCImpl::customEvent(QEvent*) ()
#4  0x00007f731b57992b in QObject::event(QEvent*) () from /gnu/store/f8zqacidi0sqfpclnzjdvbc67vyka55a-qt-5.9.3/lib/libQt5Core.so.5
#5  0x00007f731b54e453 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /gnu/store/f8zqacidi0sqfpclnzjdvbc67vyka55a-qt-5.9.3/lib/libQt5Core.so.5
#6  0x00007f731b550afb in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /gnu/store/f8zqacidi0sqfpclnzjdvbc67vyka55a-qt-5.9.3/lib/libQt5Core.so.5
#7  0x00007f731b5a1703 in ?? () from /gnu/store/f8zqacidi0sqfpclnzjdvbc67vyka55a-qt-5.9.3/lib/libQt5Core.so.5
#8  0x00007f7316faf327 in g_main_context_dispatch () from /gnu/store/80fy0frgfzraw0a9c46sicj3rm3zyvay-glib-2.52.3/lib/libglib-2.0.so.0
#9  0x00007f7316faf558 in g_main_context_iterate.isra () from /gnu/store/80fy0frgfzraw0a9c46sicj3rm3zyvay-glib-2.52.3/lib/libglib-2.0.so.0
#10 0x00007f7316faf5fc in g_main_context_iteration () from /gnu/store/80fy0frgfzraw0a9c46sicj3rm3zyvay-glib-2.52.3/lib/libglib-2.0.so.0
#11 0x00007f731b5a0d4f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /gnu/store/f8zqacidi0sqfpclnzjdvbc67vyka55a-qt-5.9.3/lib/libQt5Core.so.5
#12 0x00007f731b54ca5a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /gnu/store/f8zqacidi0sqfpclnzjdvbc67vyka55a-qt-5.9.3/lib/libQt5Core.so.5
#13 0x00007f731b5552e4 in QCoreApplication::exec() () from /gnu/store/f8zqacidi0sqfpclnzjdvbc67vyka55a-qt-5.9.3/lib/libQt5Core.so.5
#14 0x0000000000423686 in main ()
```
Unfortunately I can't quite figure out how to get Guix to give me debug symbols for Murmur (or rather how to get gdb to accept them regardless of their invalid CRC), so the above backtrace is basically all I got.

This may have happened only twice in the last three days even though I've been heavily tinkering with gRPC support for Mumo.
The first time I didn't even have core dumps enabled, so I'm only guessing that it's the same thing.

### PR DESCRIPTION
**Pull request by bontibon**
Fixes #3299

### CODE REVIEW

**Comment by bontibon** [comment]
@Johni0702 I believe this patch should fix the crash you were experiencing; it fixed it for me after I replicated the issue.

**Comment by bontibon** [comment]
There are a couple of places I missed where this check should be added. Give me a few hours.

**Comment by mkrautz** [comment]
Squash typo fix into previous commit?

**Comment by bontibon** [comment]
@mkrautz  Done

**Comment by mkrautz** [comment]
BTW, please let Travis CI and AppVeyor finish sucessfully before merging, unless it's very urgent.

Also, we tend to use the following template for pull requests:

    Merge PR #<PRNum>: <PRTitle>

    <OptionalPRBody>

The title is more descriptive than a username and branch, especially if you're grouping commits together in a "feature PR". Then the PR title and message (if present) is used to describe the feature as a whole, and any information that belongs there. This allows the individual commit titles/messages to only concern themselves with their own content.

Typically, the OptionalPRBody is the text in the first post of the PR.
If it's a single commit PR, or a PR body doesn't make sense, feel free to leave it out.

No worries though. I hadn't told you. :-)

**Pull request merged**
