### PR TITLE
BUILD(crypto): Migrate to OpenSSL 3.0 API

### LINKED ISSUE #4266: Mumble 1.3.1 build failed with new OpenSSL 3.0.0 alpha3 - undeclared identifier 'CRYPTO_MEM_CHECK_ON'
**Describe the bug**
When build new Mumble 1.3.1 for OpenMandriva Cooker I see build error:
```
make[2]: Leaving directory '/builddir/build/BUILD/mumble-1.3.1/src/mumble'
../SelfSignedCertificate.cpp:48:22: error: use of undeclared identifier 'CRYPTO_MEM_CHECK_ON'
          if (CRYPTO_mem_ctrl(CRYPTO_MEM_CHECK_ON) == -1) {
                              ^
1 error generated.
make[2]: *** [Makefile.Release:2865: ../../release/.obj/mumble/SelfSignedCertificate.o] Error 1
make[2]: *** Waiting for unfinished jobs....

```
**Steps to Reproduce**
1. Build on OpenMandriva Cooker
1. Or on any distro with new OpenSSL 3.0.0 alpha3
2. See build error 

**Expected behavior**
Compilation will be successful

**Desktop (please complete the following information):**
 - OS: [Linux OpenMandriva Cooker]
 - Version: [e.g. Mumble 1.3.1]
 - LLVM/Clang 10.1 compiler

**Additional context**
The problem is probably the new OpenSSL 3.0.0 alpha3. When building with the old version 1.1.1 the build is successful.

Here is build content: https://abf.openmandriva.org/build_lists/780879
Full build log: https://file-store.openmandriva.org/api/v1/file_stores/d739d03599c19d1f9decd35d59200e05757122b7.log?show=true

### LINKED ISSUE #5277: Deprecation warning when built against OpenSSL 3.0
**Describe the bug**
Cannot build under macos.

**Steps to Reproduce**
Follow steps as described.
cmake ..
Deprecation errors appear: "error: 'EVP_PKEY_assign' is deprecated [-Werror,-Wdeprecated-declarations]"

**Desktop (please complete the following information):**
 - OS: MacOS 11.6
 - Latest mumble sources

### PR DESCRIPTION
**Pull request by TerryGeng**
OpenSSL 3.0 deprecated several low-level APIs and the usage of them
caused errors/warnings that prevent the binary from being built against
OpenSSL 3.0.
Some primitive efforts have been made in #5317 but were incomplete.
This commit follows https://www.openssl.org/docs/man3.0/man7/migration_guide.html
and clears all errors/warnings related to the usage of deprecated APIs.

Fixes #5277
Fixes #4266

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Comment by TerryGeng** [comment]
Ready for merging.

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
Thank you for working on this! :+1: 

I tend to not backport this to the 1.4.x branch due to how close we are to creating the stable release - at this point I would rather not risk introducing a crypto-related issue into this series.
Would you consider a backport to be more or less required or would you be fine with only having these changes in master?

**Comment by TerryGeng** [comment]
@Krzmbrzl No problem :)

**Comment by Krzmbrzl** [comment]
Oh think you misunderstood my question :sweat_smile: 
I was actually asking your opinion on whether you think the backport should be done or not. Creating the actual backport would not have been an issue ^^
But presumably folks still want to compile 1.4.x for some time, so having the compatibility to OpenSSL 3.0 in there is probably a good thing :thinking:

**Comment by TerryGeng** [comment]
Yeah... That's what I'm thinking. It's always a good idea to replace deprecated APIs. Making a backport is not hard anyway ;).

**Comment by TerryGeng** [comment]
> I tend to not backport this to the 1.4.x branch due to how close we are to creating the stable release

In this case, let's wait for some feedback before we merge the backport to 1.4.x.

**Comment by Krzmbrzl** [comment]
Sounds good to me

**Pull request merged**
