### PR TITLE
Update World of Warcraft 32-bit plugin to build 20444

### PR DESCRIPTION
**Pull request by fwaggle**
Untested because I have no friends. :( Debug printf()s look correct, and
I've gotten away with it before.

### CODE REVIEW

**Comment by mkrautz** [comment]
Use "32-bit" instead of "x32" in the plugin description, please. "x32" is confusing, and at worst incorrect. Microsoft uses the names x86 and x64 for the architectures. But x32 is the 32-bit-pointers-on-x86-64 ABI for Linux.

**Comment by mkrautz** [comment]
@fwaggle says this is out of date due to a new WoW patch.

**Comment by fwaggle** [comment]
@mkrautz Yep will hopefully update it today after I'm done with course work.

**Comment by fwaggle** [comment]
Okay, updated and checked - works with current release version. Since my build environment behaves correctly, I also tested it (for the first time in a long time) with two WoW clients and it seems to do what it says on the box.

**Comment by mkrautz** [comment]
Landed as 263607f5781dba04fdd7be8ac52311b4c77fcd27.

**Pull request closed without merging**
