### PR TITLE
BUILD(installer): Include g15-helper

### LINKED ISSUE #4708: [1.4.0 snapshot] missing G15-helper
**Describe the bug**
`mumble-g15-helper.exe` is missing

**Steps to Reproduce**
Check file structure

**Expected behavior**
Should be present

**Desktop:**
 - OS: Windows 10
 - Version: `1.4.0~2020-12-24~gdb4b6be~snapshot`

**Additional context**
This was first discussed in #4701. I closed that issue because it's not actually related to GKeys.

_Originally posted by @davidebeatrici in https://github.com/mumble-voip/mumble/issues/4701#issuecomment-762400012_

The file is missing from the list:
https://github.com/mumble-voip/mumble/blob/4b36f0f9a7892d03fbac4f40f4862cfb3ab46504/installer/ClientInstaller.cs#L79-L107

### PR DESCRIPTION
**Pull request by Krzmbrzl**
Fixes #4708

### CODE REVIEW

**Review by ZeroAbility — APPROVED** [review]
Looks good to me.

**Review by davidebeatrici — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
For some reason the CI build failed. I am not yet sure why though.

**Comment by davidebeatrici** [comment]
The file is called `mumble-g15-helper.exe`:
https://github.com/mumble-voip/mumble/blob/4b533dce5252833aad452f2b39bcd1c305a58796/g15helper/CMakeLists.txt#L22-L26

**Comment by Krzmbrzl** [comment]
Good catch! Let's see if that fixes the issue :)

**Pull request merged**
