### PR TITLE
Positional audio vector clamping

### PR DESCRIPTION
**Pull request by rawnar**
This is my implementation of vector clamping for positional audio.

### CODE REVIEW

**Comment by felix91gr** [comment]
Is this PR still valid?

**Comment by Krzmbrzl** [comment]
From the comments it seemed as if the PR was ready. Given that it hasn't been merged though, I don't know whether there were things that were considered to need improvements :thinking:

**Comment by rawnar** [comment]
At the time I did not apply the last pull request from Kissaki, so that alteration is not in my branch. And as the original code is 9 years old there probably will have some merge problem. It would also be handy to add an option in the audio output configuration to select this feature.

There was also a comment on the forum that it would be good to keep a little volume on the neighboring loudspeaker. At the moment when the source is positioned perfectly at the location of a loudspeaker the neighboring speakers are mute.

**Comment by Krzmbrzl** [comment]
@rawnar thanks for the update.

Any chance you have the time and motivation to polish this PR up, so we can get it merged? This might be the fastest solution as I suspect that you understand your code the quickest :D

**Comment by rawnar** [comment]
@Krzmbrzl: I will give it a try. Been a while since I coded anything.

**Comment by Kissaki** [comment]
It’s been long ago and I would have to read into it again as well. So I’m dropping out for now.

Feel free to poke me again regarding the PRs I seem to have made to your branch or if you need help or something.

**Comment by Kissaki** [comment]
If you need help with the merge/rebase conflicts or something maybe I could find some time this weekend.

**Comment by rawnar** [comment]
No problem Kissaki. I will give it a try this weekend or the next.

**Comment by cheesy** [comment]
FWIW, I was maintaining a working branch of this on a more recent mumble for a while. I'm sure it'd still be hell to merge but you might find it slightly easier?

https://github.com/cheesy/mumble/commits/positional_audio

**Comment by rawnar** [comment]
Thanks cheesy. I will have a look at it.

**Comment by Krzmbrzl** [comment]
Closing as stale

**Comment by rawnar** [comment]
I am fine with that. No time at the moment to update the patch. If I manage to make a new implementation I will file a new pull request.
________________________________
Van: Robert Adam <notifications@github.com>
Verzonden: vrijdag 20 november 2020 08:01
Aan: mumble-voip/mumble <mumble@noreply.github.com>
CC: Mark-Willem Jansen <markwillem@hotmail.com>; Assign <assign@noreply.github.com>
Onderwerp: Re: [mumble-voip/mumble] Positional audio vector clamping (#35)


Closing as stale

**Pull request closed without merging**
