### PR TITLE
Add configurable "You joined channel" and "You have been moved to channel by..." messages

### PR DESCRIPTION
**Pull request by davidebeatrici**
As requested in #1966.

### CODE REVIEW

**Comment by davidebeatrici** [comment]
I accidentally pushed the branch to the master repository, sorry.

**Comment by davidebeatrici** [comment]
@mkrautz Sure!

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/mumble/pull/3355

**Comment by mkrautz** [comment]
@davidebeatrici Can you resync against master? :)

**Comment by davidebeatrici** [comment]
@mkrautz I was pushing at the exact moment you wrote. :)

**Pull request merged**
