### PR TITLE
DOCS(protocol): Add network protocol doc file

### PR DESCRIPTION
**Pull request by Kissaki**
We have documentation in the mumble-protocol repository and generated website.

The doc file in this repository serves as a simple reference pointing to those.

See also [mumble-www #59](https://github.com/mumble-voip/mumble-www/issues/59)

### CODE REVIEW

**Comment by Kissaki** [comment]
was referencing the wrong ticket id…

**Comment by Krzmbrzl** [comment]
I think I would prefer getting rid of that extra site and repo in favor of integrating everything here 👀

**Comment by Kissaki** [comment]
I've always thought so too. :)

**Review by Krzmbrzl — APPROVED** [review]

**Comment by davidebeatrici** [comment]
Agreed.

**Review by davidebeatrici — APPROVED** [review]

**Pull request merged**
