### PR TITLE
FreeBSD fixes

### PR DESCRIPTION
**Pull request by feld**
These should not be overly intrusive. FreeBSD has been carrying these patches for a while, but it would be nice to have them upstream.

### CODE REVIEW

**Comment by mkrautz** [comment]
@feld - Closed this by accident? I can see in my FreeBSD install that these are still necessary...

**Comment by feld** [comment]
yeah, I guess I tried to kill the patch to overlay_gl/overlay.c and ended up closing the entire pull request.

**Comment by mkrautz** [comment]
I recently landed various FreeBSD 10 fixes. I believe everything you fixed here should be fixed in master now, as well.

**Comment by feld** [comment]
Looks good from what I can tell. I've run a build with all those patches removed and it worked. I think 1.3.0 (mumble) is going to support FreeBSD well. I have to test some murmur builds yet, but I don't expect any significant issues.

**Pull request closed without merging**
