### PR TITLE
WIP: Build Murmur with gRPC support by default

### PR DESCRIPTION
**Pull request by HeroCC**
This PR builds Murmur with gRPC support by default. I raised the ticket #3429 and this PR resolves that. I put some thoughts in there, but essentially I think that since gRPC has had almost 3 years to mature since initial support in Murmur was added, it should be enabled by default. 

I changed the 'grpc' build config to 'no-grpc', and updated the INSTALL file to match. I also added grpc as a dependency to build on OSX and Linux, but I would appreciate some help verifying that those work and adding support for Windows builds.

I tested this on Arch Linux with the build command `qmake-qt5 -recursive CONFIG+=no-client CONFIG+=no-ice && make` and murmur built with gRPC support successfully (as seen in the logs).

I applied for a Wiki account as well, and if this gets merged I would be happy to add applicable steps and dependencies to the wiki articles.

Thanks all!

### CODE REVIEW

**Comment by Kissaki** [comment]
Thank you for the effort.

Do we have grpc clients we can test this with? Grpc may have matured, but I would like to verify it (still) works (our side of things with current grpc lib).

**Comment by bontibon** [comment]
@Kissaki: Testing can be done with https://github.com/layeh/murmur-cli

**Comment by davidebeatrici** [comment]
Unfortunately `libgrpc-dev` is not available for Ubuntu 14.04.

**Comment by davidebeatrici** [comment]
Superseded by #3480.

**Pull request closed without merging**
