### PR TITLE
FIX(server): Add missing line breaks to --help output

### PR DESCRIPTION
**Pull request by felixsinger**
### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Review by Krzmbrzl — CHANGES_REQUESTED** [review]
The commit type should be `FIX` as `FORMAT` is usually only used for formatting the source code itself (which is never visible from the running application) whereas this fixes an issue with the actual program's output.
And the scope should be `server` and not `murmur` (we are in the process of deprecating the term "murmur").

So overall it should be `FIX(server): ...`

**Comment by felixsinger** [comment]
Thanks for the clarification!

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
No problem :)

**Comment by felixsinger** [comment]
Are you planning to backport this to the 1.4.x branch?

**Comment by Krzmbrzl** [comment]
Given that this fixes a bug, yes a backport is due

**Comment by Krzmbrzl** [comment]
Thanks for fixing this :+1:

**Comment by felixsinger** [comment]
Great, thanks :)

**Pull request merged**
