### PR TITLE
Replace deprecated constructs

### PR DESCRIPTION
**Pull request by Krzmbrzl**
Our failing macOS CI indicates that there are a few constructs in our code-base that are considered deprecated. This PR attempts to fix that.

### CODE REVIEW

**Comment by Krzmbrzl** [comment]
Okay we have a problem here.

Ubuntu 16.04 (Xenial) ships with protobuf 2.6.1 from 2014 ([Ubuntu-pkg](https://packages.ubuntu.com/xenial/devel/protobuf-compiler), [protobuf-release](https://github.com/protocolbuffers/protobuf/releases/tag/v2.6.1))
Ubuntu 18.04 (Bionic) ships with protobuf 3.0 from 2016 ([Ubuntu-pkg](https://packages.ubuntu.com/bionic/devel/protobuf-compiler), [protobuf-release](https://github.com/protocolbuffers/protobuf/releases/tag/v3.0.0))

The macOS CI complains that `ByteSize()`  is deprecated and one should use `ByteSizeLong()` instead. This appears to have been introduced in [protobuf 3.4](https://github.com/protocolbuffers/protobuf/releases/tag/v3.4.0) from 2017.
The macOS CI uses protobuf 3.11

Thus we can't fix the deprecated-warning as that would break the compatibility to the Ubuntu LTSs. What should we do about it @davidebeatrici ?

**Comment by davidebeatrici** [comment]
I would check the protobuf version and use `ByteSize()` or `ByteSizeLong()` accordingly.

**Comment by Krzmbrzl** [comment]
For reference: The macro holding the protobuf-version is found here: https://github.com/protocolbuffers/protobuf/blob/5e014c2ddf1e4e46305fd9c7847d8f6423f80fcf/src/google/protobuf/stubs/common.h#L82-L84

**Comment by davidebeatrici** [comment]
The macOS build failed because of a deprecated Qt function:
```cpp
../HostAddress.cpp:142:7: error: 'sprintf' is deprecated: Use asprintf(), arg() or QTextStream instead [-Werror,-Wdeprecated-declarations]
                        qs.sprintf("[%x:%x:%x:%x:%x:%x:%x:%x]", ntohs(shorts[0]), ntohs(shorts[1]), ntohs(shorts[2]), ntohs(shorts[3]), ntohs(shorts[4]), ntohs(shorts[5]), ntohs(shorts[6]), ntohs(shorts[7]));
                           ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qstring.h:381:5: note: 'sprintf' has been explicitly marked deprecated here
    QT_DEPRECATED_X("Use asprintf(), arg() or QTextStream instead")
    ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qglobal.h:294:33: note: expanded from macro 'QT_DEPRECATED_X'
#  define QT_DEPRECATED_X(text) Q_DECL_DEPRECATED_X(text)
                                ^
/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qcompilerdetection.h:676:55: note: expanded from macro 'Q_DECL_DEPRECATED_X'
#    define Q_DECL_DEPRECATED_X(text) __attribute__ ((__deprecated__(text)))
                                                      ^
```

**Comment by Krzmbrzl** [comment]
Yeah I saw it. Just didn't have the time to fix it xD
I assume there are a few more after that as well. But I have to rely on the CI to tell me where they are as I don't have a Mac ^^

**Comment by deluxghost** [comment]
the build process fails on the first warning, there are more than two of these

**Comment by Krzmbrzl** [comment]
Wow Qt made some really stupid design decisions in terms of what to be labeled deprecated...

**Pull request merged**
