### PR TITLE
Fix #2586: Use QAtomicInt continuously-existing methods

### LINKED ISSUE #2586: Qt 4 build error via precise PPA
g++ -c -include release/murmurd -m64 -pipe -fvisibility=hidden -Wall -Wextra -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -g -isystem ../mumble_proto -isystem murmur_ice -O2 -pthread -Wall -W -D_REENTRANT -DNO_UPDATE_CHECK -DPLUGIN_PATH=/usr/lib/mumble -DMUMBLE_VERSION=1.3.0~1643~g4add9ce~snapshot-1~ppa1~precise1 -DHAVE_LIMITS_H -DHAVE_ENDIAN_H -DRESTRICT=__restrict__ -DMUMBLE_VERSION_STRING=1.3.0 -DQ_DECL_OVERRIDE= -DQ_DECL_FINAL= -DMURMUR -DUSE_DBUS -DUSE_ICE -DUSE_BONJOUR -D_REENTRANT -DQT_NO_DEBUG -DQT_DBUS_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtDBus -I/usr/include/qt4 -I../../src -I. -I../mumble_proto -Imurmur_ice -I../../3rdparty/qqbonjour-src -I/usr/include/avahi-compat-libdns_sd -Irelease -o release/ServerDB.o ServerDB.cpp
	Server.cpp: In member function ‘void Server::sendMessage(ServerUser*, const char*, int, QByteArray&, bool)’:
	Server.cpp:897:20: error: ‘class QAtomicInt’ has no member named ‘load’
	make[3]: *** [release/Server.o] Error 1
	make[3]: *** Waiting for unfinished jobs....
	ServerDB.cpp: In member function ‘void Server::updateChannel(const Channel*)’:
	ServerDB.cpp:1691:25: warning: ‘id’ may be used uninitialized in this function [-Wuninitialized]
	make[3]: Leaving directory `/«PKGBUILDDIR»/src/murmur'
	make[2]: *** [release] Error 2
	make[2]: Leaving directory `/«PKGBUILDDIR»/src/murmur'
	make[1]: *** [sub-src-murmur-sub_Release_ordered] Error 2
	make[1]: Leaving directory `/«PKGBUILDDIR»'
	make: *** [build-arch-stamp] Error 2
	dpkg-buildpackage: error: debian/rules build gave error exit status 2

### PR DESCRIPTION
**Pull request by Kissaki**
load() exists only in Qt5, int() exists only in Qt<5 and Qt>5.3.
The fetchAndAddRelaxed method exists in all these Qt versions we support.

### CODE REVIEW

**Comment by mkrautz** [comment]
I don't like that we're turning it into a store as well.

I think the better solution woul be to add a getter and setter to ServerUser, and #ifdef in there... :(

**Comment by mkrautz** [comment]
Or an inline helper compat function...

**Comment by mkrautz** [comment]
(I have a counter-PR pending)

**Comment by mkrautz** [comment]
How about https://github.com/mumble-voip/mumble/pull/2593?

**Comment by Kissaki** [comment]
Alright

**Pull request closed without merging**
