### PR TITLE
compiler.pri: on Windows, treat MSVC linker warnings as errors.

### PR DESCRIPTION
**Pull request by mkrautz**

### CODE REVIEW

**Comment by hacst** [comment]
LGTM

**Comment by mkrautz** [comment]
We need a buildenv update for this to work. I will land after I have updated the buildenvs on the Windows builder.

**Comment by hacst** [comment]
Hm. In what way is that related to the build-env? Does its configuration create warnings during linking of mumble?

**Comment by mkrautz** [comment]
Yep.

**Comment by mkrautz** [comment]
Fixed by 

https://github.com/mumble-voip/mumble-releng/commit/24114bc7e053a61a241957e4085cd48b79e407f7

and

https://github.com/mumble-voip/mumble-releng/commit/31de0229a55b63961cb8da5a3859345e7e0a665e

**Comment by mkrautz** [comment]
Landed as 34cbd3cb365e66bc88abc2e653880efa68bee67b.

**Pull request closed without merging**
