### PR TITLE
Use RSA_generate_key_ex instead of RSA_generate_key for generating Murmur's self-signed certificate.

### PR DESCRIPTION
**Pull request by mkrautz**
This series of commits refactors our code to generate self-signed certificates to be more strict about errors.
In the process, the code is refactored out into its own function.

### CODE REVIEW

**Comment by Kissaki** [comment]
I went commit by commit. They were really well set up.

**Comment by mkrautz** [comment]
There's a logic bug regarding freeing the private key. I'm looking into it.

**Comment by mkrautz** [comment]
Fixed the typo as well as the logic error.

The problem was that we freed both the RSA * and EVP_PKEY *. However, that is not valid after we've assigned the RSA key to the EVP_PKEY.

**Comment by Kissaki** [comment]
What do you want me to look at (again)? :P

**Comment by mkrautz** [comment]
No, it's ok :)

**Comment by mkrautz** [comment]
Thanks for the review. Glad it was easy to read.

**Pull request merged**
