### PR TITLE
MAINT(build): Modify helper folder and scripts to use custom zeroc-ice port

### LINKED ISSUE #5624: Dependency scripts may have issues after merge of ZeroC Ice port to vcpkg
### Description

A ZeroC Ice port was recently merged to vcpkg: 

https://github.com/microsoft/vcpkg/pull/23764

By default, it builds with C++11 support and does not appear to have a feature/option to build using the C++98 project types. Our script for Windows checks for the presence of the folder `zeroc-ice` and if it does not exist it copies our custom port files to a new directory with that name. We need to move the vcpkg port folder in `vcpkg/ports` to something like `vcpkg/ports/zeroc-ice_msbuild` so we can add our custom port.

### Steps to reproduce

1. Run the script in `mumble/scripts/vcpkg` to install vcpkg and dependency packages.
2. zeroc-ice package installs and produces a C++11 ice library which our project does not support.

### Mumble version

_No response_

### Mumble component

Server

### OS

Windows

### Reproducible?

Yes

### Additional information

Will most likely affect macOS and Linux, possibly CI

### Relevant log output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by ZeroAbility**
Fixes #5624

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Review by davidebeatrici — APPROVED** [review]

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
The commit's TYPE shouldn't be `FIX`. That one is only used for fixing bugs in the final software. As this commit changes non-code files only, I think `MAINT` is the proper type here.

**Comment by davidebeatrici** [comment]
Or `BUILD` maybe?

**Comment by ZeroAbility** [comment]
I chose `FIX` because the upstream change creates a bug and makes our script install something that breaks the build process. Do you need me to change it or can we just merge this?

**Comment by Krzmbrzl** [comment]
> Or BUILD maybe?

I thought about that, too but the script itself is not really related to building Mumble itself. It is only a helper script and for those we usually use MAINT. Though I guess, I could live with BUILD as well 🤷

> I chose FIX because the upstream change creates a bug and makes our script install something that breaks the build process. Do you need me to change it or can we just merge this?

Yeah, but as I said: FIX is reserved for bugs in Mumble itself. And since we use these tags to auto-generate the changelog, I would indeed ask you to change your commit accordingly.

**Comment by ZeroAbility** [comment]
Commit updated.

**Comment by Krzmbrzl** [comment]
Thanks :heart:

**Pull request merged**
