### PR TITLE
DOCS(docker): Docker compose

### PR DESCRIPTION
**Pull request by TheNamelessWonderer**
This commit adds an example docker-compose.yml file. This makes it much easier to create a docker image of mumble and gives examples about how the mounts and ports etc should work.

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Review by Krzmbrzl — CHANGES_REQUESTED** [review]
Ah okay - this is not documentation and as such should not be in the `docs` folder. I guess for something like this, the best place currently seems to be the `scripts` directory...

Also note that your commit message does _not_ follow our guidelines (your PR-title however, does). And given that this is not about documentation, I think the better TYPE for your commit is `MAINT(docker):`.

**Comment by TheNamelessWonderer** [comment]
Sorry about this I have changed the title, the message body and moved it to the scripts folder. I'd be glad to open another pull request afterwards with some documentation linking to this file as an example.

**Comment by Krzmbrzl** [comment]
Please squash all your commits together and please follow our commit guidelines for wording the _commit message_. Also that merge commit shouldn't be part of this PR. If you need to update your fork against current master, please perform a `git pull --rebase` to perform a rebase rather than a merge :)

(We are a bit pedantic about the "cleanliness" of our commit history)

**Comment by Krzmbrzl** [comment]
The old commits are still present and the new one does still not conform to our commit guidelines...

**Comment by TheNamelessWonderer** [comment]
Sorry about that I wasn’t quite done. I’m new to pull requests so I’ll mark it as draft and clean up the old requests.

**Comment by Krzmbrzl** [comment]
Alright then, don't worry. Take your time and don't be afraid to ask questions :)

**Comment by TheNamelessWonderer** [comment]
I'm sorry about all this. Hopefully this is alright now. If there are any more mistakes let me know!

**Review by Krzmbrzl — CHANGES_REQUESTED** [review]
`Docs` should be `DOCS` in the commit message and it being directly followed by `Documentation` is redundant :)
I suggest a commit message such as
```
DOCS(docker): Docker compose
```

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
Thank you for your contribution :+1:

**Comment by TheNamelessWonderer** [comment]
Thank you for being patience with me!

**Pull request merged**
