### PR TITLE
DOCS(build): Add a missing dependency to static build instructions.

### PR DESCRIPTION
**Pull request by Lucius-Q-User**
### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Comment by Krzmbrzl** [comment]
Indeed :+1: 

We also have to update the scripts at https://github.com/mumble-voip/mumble/tree/master/scripts/vcpkg

Do you want to add that in your commit as well or do you want me to add it for you? :)

**Comment by Lucius-Q-User** [comment]
Those files already have qt5-translations dependency in them

**Comment by Krzmbrzl** [comment]
Oh yes indeed. My bad :facepalm:

**Comment by Krzmbrzl** [comment]
Thanks for adding this to the docs :+1:

**Pull request merged**
