### PR TITLE
Set target macOS version to 10.9, fix deprecated stuff, restore Azure Pipelines build

### PR DESCRIPTION
**Pull request by davidebeatrici**
`libstdc++` was deprecated with Xcode 8 and is not supported in Xcode 10.

The new library is `libc++`, available with macOS 10.9+.

Setting the target macOS version to 10.9 revealed a lot of warnings due to the use of deprecated stuff.

The build also failed because the i386 architecture is not supported anymore.

This pull request fixes all warnings/errors and restores the Azure Pipelines build, which was removed in bb6416c01381ffa39bbc07c1833f21da231e252d.

https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes

### CODE REVIEW

**Comment by ZingBlue** [comment]
This is awesowe! I hope it fixes most of the issues with the Mac build.

**Comment by davidebeatrici** [comment]
What issues are you referring to, specifically?

**Comment by ZingBlue** [comment]
On a few of my friend's Macs the chat does not show up and trying to open the settings menu crashes Mumble. I can't reproduce these issues because I don't have a Mac, but they are pretty important and cause havoc when we VC over Mumble.

**Comment by davidebeatrici** [comment]
Oh, that's a big issue.

It would be great if you could provide a backtrace after Mumble crashes.

**Comment by ZingBlue** [comment]
Sure, I'll ask him to provide a backtrace. Do you also want the backtrace for the other person who has chat issues?(I haven't used backtrace, I'm not sure if it can help in this case or not).

**Comment by davidebeatrici** [comment]
> Sure, I'll ask him to provide a backtrace.

Excellent, thank you.

> Do you also want the backtrace for the other person who has chat issues?(I haven't used backtrace, I'm not sure if it can help in this case or not).

Unfortunately not, a backtrace is mostly helpful when a process freezes or crashes.

However, we're aware of the issue: it's not related to macOS, we received reports of it happening on Linux as well.

I didn't investigate what causes it yet, but I'm pretty sure it happens when the size of the chat text box is invalid.

**Comment by davidebeatrici** [comment]
> I didn't investigate what causes it yet, but I'm pretty sure it happens when the size of the chat text box is invalid.

Confirmed in #3817.

**Comment by ZingBlue** [comment]
Where can I find the backtrace, is it the console.txt under ``...\AppData\Roaming\Mumble``?

**Comment by davidebeatrici** [comment]
`console.txt` contains the console log, you have to run Mumble through a debugger in order to get a backtrace.

However, a crash dump should be generated automatically:
https://github.com/mumble-voip/mumble/blob/de8a92ea53fc6a2967eb04e03cc156cbce8a6710/src/mumble/CrashReporter.cpp#L105-L137

The crash reporter window should show up when you run Mumble after it crashed.

**Pull request merged**
