### PR TITLE
CHANGE(server): Make tracy build optional

### PR DESCRIPTION
**Pull request by 0xC0ncord**
Instead of always building and linking Tracy even if it's disabled, make tracy completely optional.

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Comment by Krzmbrzl** [comment]
Why?

The approach you chose seems overly complicated and breaks as soon as we want to use another Tracy macro. This does not seem like a good idea to my as it will only increase future maintenance work...

**Comment by 0xC0ncord** [comment]
> Why?

I don't see the point in compiling in Tracy support if flipping it on means compiling Mumble again. The current implementation adds an external dependency that is essentially dead code if it wasn't enabled at build time.

> The approach you chose seems overly complicated and breaks as soon as we want to use another Tracy macro.

I agree it's not very elegant... What if instead we moved the inclusion of the Tracy headers to another header that handles all of this logic itself? That way we don't need to make any changes to the source files apart from just including this new header.

**Comment by Krzmbrzl** [comment]
But why is compiling Tracy a problem? It doesn't take long and it doesn't introduce additional dependencies. 
And there is no runtime effect of having built Tracy even though it was disabled.

I think maintaining that extra header is more bothersome than simply compiling Tracy, even if it might not be needed 👀

**Comment by 0xC0ncord** [comment]
Tracy itself is the dependency that is added:
```
# lddtree mumble-server | grep Tracy
    libTracyClient.so => /usr/lib64/libTracyClient.so
```
This is more of a packaging issue than a runtime or compilation one.

**Comment by Krzmbrzl** [comment]
Then maybe the solution could be as simple as building Tracy as a static library instead. That should eliminate this dependency, shouldn't it?

**Comment by 0xC0ncord** [comment]
> Then maybe the solution could be as simple as building Tracy as a static library instead. That should eliminate this dependency, shouldn't it?

I agree this is probably the best solution.

**Comment by Krzmbrzl** [comment]
Please see #5846 and let me know whether that fixes the issue for you - on my system the Tracy lib has been built statically all along, so I can't really verify that my changes have the desired effect on other systems as well :shrug:

**Comment by 0xC0ncord** [comment]
> Please see #5846 and let me know whether that fixes the issue for you - on my system the Tracy lib has been built statically all along, so I can't really verify that my changes have the desired effect on other systems as well shrug

Just tried it out and it seems to work! Thanks!

**Pull request closed without merging**
