### PR TITLE
Build/package murmur in a docker image

### LINKED ISSUE #3688: Provide official Docker image for murmur
It would be nice to have an official image of murmur for containerized deployments.  I can take a crack at this if I get some guidance for what version to target (1.2.x or 1.3.x)

### PR DESCRIPTION
**Pull request by gclawes**
Closes #3688.

### CODE REVIEW

**Comment by davidebeatrici** [comment]
From Cirrus CI:
```
error building image: error building stage: lstat /workspace/scripts/murmur.ini: no such file or directory
```

**Comment by gclawes** [comment]
Does Cirrius CI support multi-stage builds?

**Comment by davidebeatrici** [comment]
Yes: https://cirrus-ci.org/guide/docker-builder

**Comment by gclawes** [comment]
Looks like the offending line is `COPY ./scripts/murmur.ini /etc/murmur/murmur.ini`, not the multi-stage copy before it.

 It builds locally in docker, is Cirrus using something else to build images?

```
Step 11/16 : COPY --from=0 /root/mumble/release/murmurd /usr/bin/murmurd
 ---> 41561da5be08
Step 12/16 : COPY ./scripts/murmur.ini /etc/murmur/murmur.ini
---> 8ab3c5a4c6d8
```

**Comment by gclawes** [comment]
This may be down to a difference between docker and kanico, I'll look into that.

**Comment by gclawes** [comment]
The build passes in DockerHub builds: https://cloud.docker.com/repository/registry-1.docker.io/gclawes/murmur/builds/06d879f1-475a-4908-8ba4-8611ee2a664d

docker build screenshot

**Comment by gclawes** [comment]
I tried switching the order of the copy statements, confirmed that it's the one for murmur.ini that's failing.  At this point I'm not sure what else to do, other than try a single-stage build.  It seems like this is down to a bug in kaniko (the builder used by Cirrus), as the build succeeds under docker locally and DockerHub.

**Comment by bendem** [comment]
have you tried copying it from the previous stage instead of the host?

**Comment by bendem** [comment]
Looks like that did it.

**Comment by gclawes** [comment]
Sounds good, let me squash that commit before this is merged.

**Comment by gclawes** [comment]
Done.

**Comment by davidebeatrici** [comment]
Thank you very much for your contribution!

**Pull request merged**
