### PR TITLE
UserModel: show muted/deafened state icon only in the right hand column

### PR DESCRIPTION
**Pull request by davidebeatrici**
See comments in #3368.

### CODE REVIEW

**Comment by bontibon** [comment]
Small issue: the icon is displayed on every user in the tree, not just self

**Comment by davidebeatrici** [comment]
Oops... I'm going to fix it.

**Comment by mkrautz** [comment]
You probably also need to update the What's This for the user icons to include Push-to-Mute.

**Comment by mkrautz** [comment]
You do that here:

https://github.com/davidebeatrici/mumble/blob/89bed115cff9f668d54693923ddc58386227eec8/src/mumble/UserModel.cpp#L597-L625

**Comment by davidebeatrici** [comment]
Done.

**Pull request merged**
