### PR TITLE
Update Simplified Chinese Translations installer

### PR DESCRIPTION
**Pull request by dingpengyu**
Modify the following entry:
  <String Id="MUMBLE_CREATE_SHORTCUT">创建桌面快捷方式</String>
  <String Id="MUMBLE_CREATE_SHORTCUT">Create Desktop Shortcut</String>
  <String Id="DESC_SectionBonjour">Bonjour现在可以在您的网络上报告和发现Murmur服务器。是否下载并运行Bonjour安装程序。</String>
  <String Id="DESC_SectionBonjour">Bonjour enables announcement and discovery of Murmur servers on your LAN. This will download and run the Bonjour installer.</String>
  <String Id="MUMBLE_SEC_DesktopShortcut">桌面快捷方式</String>
  <String Id="MUMBLE_SEC_DesktopShortcut">Desktop shortcut</String>
  <String Id="DESC_DesktopShortcut">创建桌面快捷方式</String>
  <String Id="DESC_DesktopShortcut">Creates a shortcut on the desktop</String>
thanks

### CODE REVIEW

**Comment by davidebeatrici** [comment]
I removed the merge commit; please enable Git's auto-rebase feature by executing `git config --global pull.rebase true`, that way merge commits are not created when you pull from a remote branch.

I also recommend to create a dedicated branch each time you want to create a pull request, so that you can open more than one at the same time and you can easily keep track of your changes.
Ideally the `master` branch in the forked repository should either be removed or kept untouched compared to the one in the origin repository.

**Comment by dingpengyu** [comment]
> I removed the merge commit; please enable Git's auto-rebase feature by executing `git config --global pull.rebase true`, that way merge commits are not created when you pull from a remote branch.
> 
> I also recommend to create a dedicated branch each time you want to create a pull request, so that you can open more than one at the same time and you can easily keep track of your changes.
> Ideally the `master` branch in the forked repository should either be removed or kept untouched compared to the one in the origin repository.

Thank you for your reminder

**Comment by davidebeatrici** [comment]
You're welcome.

**Comment by dingpengyu** [comment]
> You're welcome.
In addition, I would like to ask, I am a blind translator. I am currently maintaining NVDA in Simplified Chinese. I also want to maintain mumble. How should I start?

Crowdin is not friendly to screen readers
thanks

**Comment by davidebeatrici** [comment]
Oh, sorry to hear that. Blindness is one of the worst things that could happen to a person.

We're currently using Transifex to handle translations: https://www.transifex.com/mumble

We have a bot that automatically creates a pull request and constantly updates it each time a string is updated, #3635 for example.

Please let me know whether Transifex has issues with screen readers and/or you know a better platform we can use.

**Comment by dingpengyu** [comment]
> Oh, sorry to hear that. Blindness is one of the worst things that could happen to a person.
> 
> We're currently using Transifex to handle translations: https://www.transifex.com/mumble
> 
> We have a bot that automatically creates a pull request and constantly updates it each time a string is updated, #3635 for example.
> 
> Please let me know whether Transifex has issues with screen readers and/or you know a better platform we can use.

Can look at this
[translate/pootle](https://github.com/translate/pootle)
thanks

**Comment by davidebeatrici** [comment]
Seems excellent! I will talk about it with the rest of the team, thank you for your suggestion.

**Comment by davidebeatrici** [comment]
Thank you very much for your contribution!

I hope one day you will be able to live a normal life.
Technology improves every day, I believe we're not far from being able to fix serious problems in human bodies.

**Comment by deluxghost** [comment]
#3613 is ignored for months, with more strings updated and qt builtin dialogs translations
@davidebeatrici

**Comment by dingpengyu** [comment]
> #3613 is ignored for months, with more strings updated and qt builtin dialogs translations
> @davidebeatrici

I used the Transifex command line tool to synchronize the latest translations yesterday.
Simplified Chinese is the latest

**Comment by deluxghost** [comment]
> > #3613 is ignored for months, with more strings updated and qt builtin dialogs translations
> > @davidebeatrici
> 
> I used the Transifex command line tool to synchronize the latest translations yesterday.
> Simplified Chinese is the latest
> If this pr does not have a particularly prominent modification, I think I can turn him off.
> What do you think?

my pr has nothing to do with transifex, it's installer translation (like your pr did but with other updates) + qt translation files (should provide translations for qt builtin dialogs, such as color dialog)

as your pr is already merged, i just resolved conflict on my branch and wait any devs' reply

**Comment by deluxghost** [comment]
i was told it should be merged before 1.3.0 released, but nothing happened, so i guess devs forget it all

**Comment by dingpengyu** [comment]
> > > #3613 is ignored for months, with more strings updated and qt builtin dialogs translations
> > > @davidebeatrici
> > 
> > 
> > I used the Transifex command line tool to synchronize the latest translations yesterday.
> > Simplified Chinese is the latest
> > If this pr does not have a particularly prominent modification, I think I can turn him off.
> > What do you think?
> 
> my pr has nothing to do with transifex, it's installer translation (like your pr did but with other updates) + qt translation files (should provide translations for qt builtin dialogs, such as color dialog)
> 
> as your pr is already merged, i just resolved conflict on my branch and wait any devs' reply

Thank you for your work, very good.

**Comment by dingpengyu** [comment]
hi deluxghost
I want to know more Mumble users. Do you have any channels?
I created a Mumble Chinese communication group, the following is a group link:
[Mumble Chinese Communication](https://jq.qq.com/?_wv=1027&k=587cSpp)
thanks

**Comment by davidebeatrici** [comment]
@deluxghost We didn't merge it for 1.3 because development was already frozen, in fact we didn't merge #3635, created by our bot.

I was actually going to request some changes in your pull request immediately after merging this one, but then I forgot about it. Sorry about that.

**Pull request merged**
