### PR TITLE
Third-party license update

### PR DESCRIPTION
**Pull request by mkrautz**
This PR updates the licenses of various third-party software that Mumble uses.

This PR is especially focused on third-party software that is shipped in our official binary distributions.

The idea is to fix mumble-voip/mumble#2071 by bundling all third-party licenses with Mumble itself.

Then, once all third-party licenses are in place, we can generate the license text for the installer by using the data we've collected.

### CODE REVIEW

**Comment by bontibon** [comment]
Tried running from the root directory:
```
  %   perl scripts/mklic.pl 
binmode() on closed filehandle $F at scripts/mklic.pl line 44.
print() on closed filehandle $F at scripts/mklic.pl line 46.
print() on closed filehandle $F at scripts/mklic.pl line 47.
print() on closed filehandle $F at scripts/mklic.pl line 48.
print() on closed filehandle $F at scripts/mklic.pl line 49.
print() on closed filehandle $F at scripts/mklic.pl line 50.
print() on closed filehandle $F at scripts/mklic.pl line 51.
print() on closed filehandle $F at scripts/mklic.pl line 52.
print() on closed filehandle $F at scripts/mklic.pl line 53.
print() on closed filehandle $F at scripts/mklic.pl line 54.
print() on closed filehandle $F at scripts/mklic.pl line 55.
print() on closed filehandle $F at scripts/mklic.pl line 56.
print() on closed filehandle $F at scripts/mklic.pl line 57.
print() on closed filehandle $F at scripts/mklic.pl line 58.
print() on closed filehandle $F at scripts/mklic.pl line 59.
print() on closed filehandle $F at scripts/mklic.pl line 60.
print() on closed filehandle $F at scripts/mklic.pl line 61.
print() on closed filehandle $F at scripts/mklic.pl line 62.
print() on closed filehandle $F at scripts/mklic.pl line 63.
print() on closed filehandle $F at scripts/mklic.pl line 64.
print() on closed filehandle $F at scripts/mklic.pl line 65.
 at scripts/mklic.pl line 18.
	main::licenseFileToVar("licenseMumble", "../LICENSE") called at scripts/mklic.pl line 68
```

Any way to make the mklic script fail early?

**Comment by bontibon** [comment]
Also, the project root directory has these two folders: **3rdPartyLicenses** and **3rdparty** (note the uppercase **P**). Might want to rename for consistency?

**Comment by mkrautz** [comment]
It's a legacy script, so I don't think we should touch it too much. Generally, we prefer scripts in Python nowadays, so a replacement would probably be written in that.

> Tried running from the root directory:
> [...]
> Any way to make the mklic script fail early?

You have to run it from the scripts directory.

> Also, the project root directory has these two folders: 3rdPartyLicenses and 3rdparty (note the uppercase P). Might want to rename for consistency?

Possibly. I created the 3rdparty dir. I prefer the lower-case version. But '3rdpartylicenses' looks wrong to me. Perhaps '3rdparty/licenses/'? I don't know. Anyway, since it has been like this for some time, I think we can let it be for now.

**Comment by davidebeatrici** [comment]
@hacst Let's do it another pull request.

**Pull request merged**
