### PR TITLE
FIX(client): Performance degradation around speex

### LINKED ISSUE #6150: Ever increasing cpu time and memory usage
### Description

Mumble slowly accumulates additional memory and as a result uses an increasing amount of CPU time.

### Steps to reproduce

1. Open mumble
2. Connect to any server with another client such that the audio output code is executed
3. Wait for some period of time. Two or more hours should produce a vast increase in resources used.

### Mumble version

1.6.0

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

I was able to find the location of the issue (not the exact cause) using Perf. It appears that a vector in `src/mumble/AudioOutputSpeech.cpp` named `s_audioCaches` increases in size over time.  Consequently, later iteration over this object creates performance issues.

The function `invalidateAudioOutputCache` is supposed to be called by speex as it was registered as a callback in the call `jitter_buffer_ctl(jbJitter, JITTER_BUFFER_SET_DESTROY_CALLBACK...`. From my logging, `invalidateAudioOutputcache` seems to rarely be called.

Rebooting mumble every hour mitigates this issue for the most part.

Using mumble on Debian at version 1.3.4-4 didn't **appear** to have the same issue (no increase in ram/cpu time over 3 hours), but I must admit that I did not edit the source code to print out the size of the vector as the code vastly differs from what is present in the newer versions.

### Relevant log output

```shell
*not log output*
An easy way to confirm this issue is to print the std::size of s_audioCaches in AudioOutputSpeech::storeAudioOutputCache. 
A correct implementation would keep the size of the object relatively low.
In this case it blows up to the thousands and beyond.
```

### Screenshots
Resources used at program open. (Note, mumble was restarted after the second screenshot hence the change in PID)
mumble_short
Resources used after 1.5 hours.
mumble_hours

### PR DESCRIPTION
**Pull request by nJ3ahxac**
Elements of a vector were failing to be cleared correctly which created performance issues.

A nuance with speex was also causing the library to fail to call a destroy callback.

Fixes #6150

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Comment by Hartmnt** [comment]
@nJ3ahxac Please run ``clang-format`` (in version 10) over the changed file to get rid of the failing PR-Check action :)

**Comment by nJ3ahxac** [comment]
@Hartmnt My bad, hopefully this fixes it. I didn't run clang-format, just looked at what it was complaining about - hopefully there are no other issues.

**Comment by Hartmnt** [comment]
Yeah, your fixes did work. Please squash the formatting commit into your existing commit :)

Other than that this MR looks good to me. I assume you have tested it and it fixes the memory/cpu leak, right? I have no easy way to test this right now.

I am also not that familiar with the whole audio processing bit in Mumble, so @Krzmbrzl or @davidebeatrici  should also take a look at this one.

**Comment by nJ3ahxac** [comment]
Squashed - yes I have tested it but I can't claim that they were exhaustive. I've used the fixed build for two days now and running mumble during this period has resulted in consistent memory + cpu usage regardless of the time it was open for. I think the maximum time it was open for was at least 8 hours, by which time I would usually see 60% cpu usage on two threads. Also the size of the vector remains stayed at 100, which is good.  Some testing in other environments apart from mine is welcome.

If you want to check if this issue still exists without waiting for hours, I'd print the size of `s_audioCaches` in the function `addFrameToBuffer` in the file `src/mumble/AudioOutputSpeech.cpp`. It should stay <= 100, but grows infinitely without the fix.

**Review by davidebeatrici — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|1.5.x|[](https://github.com/mumble-voip/mumble/pull/6159)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/mumble-voip/mumble/actions/runs/5426496639) for details

**Comment by davidebeatrici** [comment]
Thank you very much for spotting this critical issue and fixing it!

> Possibly related: #3406 #1497

The issue was introduced much later, in #5594.

**Pull request merged**
