### PR TITLE
DOCS: Update Debian Build-Dependencies

### PR DESCRIPTION
**Pull request by diederikdehaas**
This MR consists of the following 3 commits:
- DOCS(build_linux): Sort Debian Build Dependencies
- DOCS(build_linux): Actually update Debian B-D: pkg-config -> pkgconf
- DOCS(build_linux): Add missing B-Ds to Debian instructions

Feel free to (ask me to) squash those into 1 (or 2) commit(s).

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Comment by diederikdehaas** [comment]
I marked the PR as Draft as I'm going to do some additional research

**Comment by Krzmbrzl** [comment]
> Feel free to (ask me to) squash those into 1 (or 2) commit(s).

Nah, I actually like the way it is right now :)

**Comment by diederikdehaas** [comment]
Most likely case will be that I'll drop ``libpipewire-0.3-dev`` and add ``libmsgsl-dev``, but I'll let you know when I finished that :-)

**Comment by diederikdehaas** [comment]
AFAIC it's now finalized :-)

**Comment by diederikdehaas** [comment]
I guess I can't remove the 'Draft' status? On GitLab you can do that by editing the title, but that didn't have the expected result here when I tried it and I haven't found a button (or sth like that) to change the status myself.

**Comment by Hartmnt** [comment]
> I guess I can't remove the 'Draft' status? On GitLab you can do that by editing the title, but that didn't have the expected result here when I tried it and I haven't found a button (or sth like that) to change the status myself.

In the upper right in the same place where you can request a review. Absolutely intuitive I know :upside_down_face:

**Comment by diederikdehaas** [comment]
> In the upper right in the same place where you can request a review. Absolutely intuitive I know

I guess that should be in the area which list the Reviewers? (where also Assignees are listed) ... yeah I don't see a button or menu item there to do that (or I'm blind), so I guess that *is* actually a permission thing.

> Or at the very bottom "Ready for review"

But I do see that, thanks!

**Comment by Hartmnt** [comment]
I guess this is fine. Any objections @Krzmbrzl @davidebeatrici ?

**Review by davidebeatrici — APPROVED** [review]

**Pull request merged**
