### PR TITLE
Update the Mumble tree to use LICENSE.header for all license headers

### PR DESCRIPTION
**Pull request by mkrautz**
Where not possible (because the BSD license requires us to keep copyright notices in-tact), we keep the original license, add the new LICENSE.header on top, and add the old license of the file to 3rdPartyLicenses.

### CODE REVIEW

**Comment by mkrautz** [comment]
PTAL

@hacst @Kissaki @fwaggle

**Comment by hacst** [comment]
Are you sure we need to do that 3rd party license thing there? Especially having them show up in the 3rd party license dialog? This makes the thing pretty much useless and unreadable.

**Comment by mkrautz** [comment]
@hacst 

I think we need it until we've been allowed to modify the license header by the copyright holder.

The idea is that this is something shippable (It's not a blocker).
This allows us some leeway contacting people in a more asynchronous manner than having them block the whole process.

If you don't agree, any ideas on how we should tackle this?

**Comment by mkrautz** [comment]
It's worth noting that technically, our shipping snapshots do not live up to the BSD-license requirements for these files, in that we don't ship our binaries with the copyright notices and the rest of the BSD-license text.

This was an attempt to fix that.

**Comment by mkrautz** [comment]
FWIW, here are the authors we need to contact. The number of times they appear is the amount of files they appear in:

	$ grep -ri "Copyright (" * | sed 's/.*, //' | sed 's,.*\-2011\ ,,' | sort | grep -iv dd0t | grep -iv natvig | grep -iv fraser | grep -iv pcgod | grep -iv kissaki | grep -iv krautz
	Andreas Messer <andi@bupfen.de>
	Bojan Hartmann <bogie@bawki.de>
	Fredrik Nordin <freedick@ludd.ltu.se>
	Gabriel Risterucci <cleyfaye@gmail.com>
	Ilmar 'Ingaras' Kruis (seaeagle1@users.sourceforge.net)
	Imre Botos <zokny@users.sourceforge.net>
	Jordan J Klassen <forivall@gmail.com>
	Lukas Orsvärn <lucas.orsv@gmail.com>
	Mark-Willem Jansen <rawnar@users.sourceforge.net>
	Mark-Willem Jansen <rawnar@users.sourceforge.net>
	Mayur Pawashe <zorgiepoo@gmail.com>
	Mike <mike@flomp.net>
	Mike <mike@flomp.net>
	Moritz Schneeweiss
	Morris Moraes <mauricioarozi@gmail.com>
	Nye Liu <nyet@nyet.org>
	Nye Liu <nyet@nyet.org>
	Nye Liu <nyet@nyet.org>
	Nye Liu <nyet@nyet.org>
	Ryan Austin <ryan@gameforcecenters.com>
	Sebastian Schlingmann <mit_service@users.sourceforge.net>
	Snares <snares@users.sourceforge.net>
	Snares <snares@users.sourceforge.net>
	Snares <snares@users.sourceforge.net>
	Snares <snares@users.sourceforge.net>
	Snares <snares@users.sourceforge.net>
	Snares <snares@users.sourceforge.net>
	Snares <snares@users.sourceforge.net>
	Snares <snares@users.sourceforge.net>
	Snares <snares@users.sourceforge.net>
	Snares <snares@users.sourceforge.net>
	Snares <snares@users.sourceforge.net>
	Snares <snares@users.sourceforge.net>
	Snares <snares@users.sourceforge.net>
	Snares <snares@users.sourceforge.net>
	Stefan Gehn <mETz AT gehn DOT net>
	Steve Hill <github@cheesy.sackheads.org>
	dark_skeleton (d-rez) <dark.skeleton@gmail.com>
	dark_skeleton (d-rez) <dark.skeleton@gmail.com>
	dark_skeleton (d-rez) <dark.skeleton@gmail.com>
	deKarl <dekarl@users.sourceforge.net>

**Comment by hacst** [comment]
Hm. If we just merge all of those into one big BSD license statement wouldn't that fulfil the terms just fine w.r.t to the binary distribution? I'm fine with having it verbose in source but exploding the license dialog to the point of no longer being readable seems counterproductive to what it's there for. IANAL so if you have doubts I won't try to argue otherwise. Such legal stuff is a pure time sink with no gain for us anyways :(

**Comment by mkrautz** [comment]
That was what we had before, so I suppose it would work.

The rest of the license text is, after all, the same.

I will try to do it.

**Comment by mkrautz** [comment]
@hacst PTAL
https://github.com/mumble-voip/mumble/compare/master...mkrautz:src-license-header-v5

In particular, this commit contains the changes I've done:
https://github.com/mumble-voip/mumble/commit/b563298a3d73aca67e2e4c5c52175758ffe4088a

**Comment by hacst** [comment]
Awesome. Much better. LGTM.

**Comment by mkrautz** [comment]
Landed via 084da530767991605b045a6183a3857f14b1b502.

**Pull request closed without merging**
