### PR TITLE
Transifex translation update

### PR DESCRIPTION
**Pull request by MumbleTransifexBot**
New translation updates available from transifex
https://www.transifex.com/organization/mumble/dashboard/mumble

### CODE REVIEW

**Comment by mkrautz** [comment]
This seems wrong. UK? I wonder if it will cause problems if we merge it.

**Comment by hacst** [comment]
Why does it seem wrong to you?

**Comment by mkrautz** [comment]
Nevermind.  I was confused by a lot of the untranslated strings in the file.

Turns out that the UK translation is quite easy -- you only have to translate the strings that have different UK spellings.

The rest of the strings can be kept untranslated.

LGTM.

**Comment by hacst** [comment]
Jupp. That works work en_UK

**Comment by mkrautz** [comment]
Also: the translation is simply called "mumble_uk", will OSes pick that up? I don't think so.

**Comment by hacst** [comment]
Should do. I thought transifex knew the language code Qt uses.

**Comment by mkrautz** [comment]
We aren't using Qt for translation loading:

https://github.com/mumble-voip/mumble/blob/master/src/mumble/main.cpp#L334

I don't think this works unless the translation is called en_UK.

**Comment by hacst** [comment]
So how do we handle this?

**Comment by mkrautz** [comment]
We should figure out:

a) What Mumble will look for when configured as English/United Kingdom.
b) We should figure out if we can get Transifex to output in that format.
or
b) We should figure out of we can get Mumble to use the format that Transifex uses.

**Comment by hacst** [comment]
So do we just merge? Shouldn't outright break anything? no?

**Comment by mkrautz** [comment]
You're right, should be fine. Feel free!

**Comment by hacst** [comment]
Merged as 81f40a2 Transifex translation update

**Pull request closed without merging**
