### PR TITLE
CHANGE(ui): Update ear.svg to fit with other icons

### PR DESCRIPTION
**Pull request by chili-b**
This change keeps the shape more or less the same, but changes the
colouring to hopefully add clarity and consistency with other icons.

Summary of changes:
 - Use single colour and negative space instead of outlines
 - ~~Change to blue tone used by the link icon to reflect the~~
   ~~similarity between listening and linking as well as to fit in~~
   ~~with the existing colour scheme~~
   Change to monochrome gray
 - Add a sound wave coming towards the ear from the right to help
   communicate the idea of "listening" a bit more

Light theme:
image

Dark theme:
image

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Review by davidebeatrici — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
I'm not sure if this blue color is the appropriate choice, since we use that color to indicate someone playing back audio. So by coloring these ears in that color as well, it might create the impression that they are actually emitting sound rather than listening :thinking: 

In general, I think it is beneficial for the ears to have a different color than the regular avatars, in order to be able to immediately distinguish them from any users in a given channel.

**Comment by chili-b** [comment]
I agree that maybe blue isn't the best choice. What about gray?
image

**Comment by Krzmbrzl** [comment]
Gray is used for the new "muted talking" talk-state (aka someone is talking but you have them locally muted). However, generally speaking this talk state is probably much less prominent than the others and thus reusing its color should be fine.

**Comment by chili-b** [comment]
I've changed the colour of the file in the commit from blue to gray

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
Thank you for your contribution :+1:

**Pull request merged**
