### PR TITLE
Backport positional audio plugins updates

### PR DESCRIPTION
**Pull request by davidebeatrici**

### CODE REVIEW

**Comment by Krzmbrzl** [comment]
Bundling changes together like this makes creating the changelog quite a bit harder so I would appreciate one backport per fix in the future :)

**Review by Krzmbrzl — APPROVED** [review]

**Comment by davidebeatrici** [comment]
Aren't the commits themselves (rather than the merge) used for the changelog?

**Comment by Krzmbrzl** [comment]
No. Only the merge commits are being processed. That's because each PR should deal with a single thing and therefore this is what we search for (whereas searching through every commit would result in a too fine-grained changelog prototyp where most entries needed to be removed manually)

**Comment by davidebeatrici** [comment]
Ah, I see.

**Pull request merged**
