### PR TITLE
Move src/bonjour to 3rdparty/qqbonjour-src and add its license to the third party license list.

### PR DESCRIPTION
**Pull request by mkrautz**
Fixes mumble-voip/mumble#2160

### CODE REVIEW

**Comment by hacst** [comment]
LGTM. Do you think we should mention explicitely that this is no longer purely a copy&paste of the original code or is that unimportant for the 3rd party list?

**Comment by mkrautz** [comment]
I actually had that ("no longer purely a c&p job") in there when I first tried to do this a couple of days ago. I scrapped that version, because the public API of QQBonjour uses dns_sd types, so it's very hard to make it a self-contained library without making major changes to it. So I opted for this version instead.

**Comment by hacst** [comment]
Fine with me.

**Comment by mkrautz** [comment]
Landed as 6beb46e6311455416b16529e55a669f137a8ac92.

**Pull request closed without merging**
