### PR TITLE
Add itch.exe as known overlay launcher

### PR DESCRIPTION
**Pull request by Kissaki**
See #3043, fix if the itch user does not use the sandboxing feature of
the itch launcher.

### CODE REVIEW

**Comment by mkrautz** [comment]
Maybe add isolate.exe as well? From ProcExp, that was the parent of the sandboxed processes. Or do you think it's unnecessary since it doesn't work at the moment?

**Comment by Kissaki** [comment]
I don't really like that `isolate.exe` is such a generic name either… :)

Do launchers have to be direct parents?

**Comment by Kissaki** [comment]
`GetProcessAncestorChain` searches parents recursively. So isolate shouldn't be necessary, if we can find itch. So I'm for leaving `isolate.exe` out.

**Comment by mkrautz** [comment]
Right, I forgot. :)

**Pull request merged**
