### PR TITLE
Replace url to sourceforge in mumble.svg by one to github

### PR DESCRIPTION
**Pull request by Natenom**

### CODE REVIEW

**Comment by mkrautz** [comment]
LGTM

**Comment by Eriner** [comment]
@Natenom #1984 includes the fixes to the other svg files as well.

**Comment by Natenom** [comment]
Didn't realize that, thank you :)

**Comment by Eriner** [comment]
@Natenom if you're curious (and ever run into a situation like this again), the following command will replace all instances of one string with another.

```
find . -type f -print0 | xargs -0 sed -r -i 's/git:\/\/mumble.git.sourceforge.net\/gitroot\/mumble/https:\/\/github.com\/mumble-voip\/mumble\//g'
```

**Pull request closed without merging**
