### PR TITLE
FIX(client, server): Fix build with Qt 6.8

### PR DESCRIPTION
**Pull request by botanegg**
### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Comment by davidebeatrici** [comment]
Two nitpicks:

1. Our preferred includes order is: local, standard library, other libraries (including Qt).
2. I would change the preprocessor if statements to use `>=` rather than `<`, as the more recent path is preferred and should appear first.

**Comment by botanegg** [comment]
image

**Comment by botanegg** [comment]
2) I'll change it. Thanks

**Comment by davidebeatrici** [comment]
Yeah, the includes order is inconsistent.

**Comment by botanegg** [comment]
@davidebeatrici fixed

**Review by davidebeatrici — APPROVED** [review]

**Pull request merged**
