### PR TITLE
Jack support from KXStudio

### PR DESCRIPTION
**Pull request by ghost**
In the past this patch was reported to cause crashes when both input and output were not set to JACK. I've successfully used this on FreeBSD for 6+ months with Input set to JACK and output to OSS without any crashes. Also, today Natenom tested this patch against git head and was not able to reproduce a crash when mixing ALSA and JACK.

### CODE REVIEW

**Comment by mkrautz** [comment]
Note to self (and others on CC, if they know): is there a newer version of this available in KXStudio now?

**Comment by mkrautz** [comment]
@Natenom says he has talked to someone who wants to improve the patch, but he doesn't know the current status.

**Comment by mkrautz** [comment]
Fixed up at https://github.com/mkrautz/mumble/compare/jack_v1

**Comment by mkrautz** [comment]
Updated: https://github.com/mkrautz/mumble/compare/jack_v2

**Comment by davidebeatrici** [comment]
Closing in favor of #3396.

**Pull request closed without merging**
