### PR TITLE
Fix building with non bundled CELT library

### PR DESCRIPTION
**Pull request by radioactiveman**
As mentioned in https://github.com/mumble-voip/mumble/pull/4466, compiling Mumble with CELT installed globally does not work currently (similar to Opus). The commit message contains more details.

See also:
- https://github.com/mumble-voip/mumble/pull/4466
- https://github.com/mumble-voip/mumble/issues/3727

### CODE REVIEW

**Comment by radioactiveman** [comment]
Interesting, the build failed due to changing the include directive. But on my system Mumble does not compile without this change.

**Comment by davidebeatrici** [comment]
The reason why it fails is that the includes are not in a `celt` subdirectory in the submodule: https://github.com/mumble-voip/celt-0.7.0/tree/5a16cda6d78cda0cd14eb13c56c65d82724842e5/libcelt

**Comment by radioactiveman** [comment]
Hmm, this also breaks the build with `-Dbundled-celt:BOOL='ON'` if CELT 0.11 is installed by the distribution.
I will remove the second commit again. The other patch for CMake should be fine, right?
But as far as I understand, your long term plans are removing CELT support anyway?

**Comment by davidebeatrici** [comment]
Yes, indeed.

**Comment by radioactiveman** [comment]
The checks pass now without the change of the include directives. Please review and merge this.

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
Thanks for the fix :+1:

**Pull request merged**
