### PR TITLE
Update winget-releaser to latest

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### CODE REVIEW

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
Speaking of which... was the 1.5 release published for winget? 🤔

**Comment by Hartmnt** [comment]
> Speaking of which... was the 1.5 release published for winget? 🤔

If the process has to be done manually upon a new release, then no. winget is not documented in our internal release docs.

**Comment by vedantmgoyal9** [comment]
I checked the logs and it looks like that the Github PAT was expired because of which a PR at microsoft/winget-pkgs repository couldn't be created.

**Comment by Krzmbrzl** [comment]
I also updated the PAT with one that doesn't expire so hopefully things should run smoothly for the coming releases.

**Pull request merged**
