### PR TITLE
TRANSLATION: Update translations from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/mumble/mumble-client/) for Mumble/Mumble Client.

Current translation status:

Weblate translation status

---

The changes were manually rebased to resolve conflicts that occured because of #4829.

### CODE REVIEW

**Comment by Kissaki** [comment]
Weblate stores/saves `&apos;` instead of `'`. We have to verify this works/shows up fine fine in the client.

**Comment by ViBE-HU** [comment]
Does this means that the Transifex translation move to Weblate?

**Comment by Krzmbrzl** [comment]
Yes indeed. Have a look at #4727

**Comment by ViBE-HU** [comment]
Thanks. Does this help to get the latest translations with new releases? Cause I still see only the old one while I continuously translating and doing a clean up on my language.

**Comment by Krzmbrzl** [comment]
> Does this help to get the latest translations with new releases? Cause I still see only the old one while I continuously translating and doing a clean up on my language.

Unfortunately not. We are aware of this problem though and are actively seeking solutions to it. See #4740

**Comment by ViBE-HU** [comment]
Oh, good to know. Gladly external language files are working on Windows. But what about Linux? Most of the time I'm on Ubuntu and AFAIK there is no way to use them on Linux, right?

**Comment by Krzmbrzl** [comment]
> But what about Linux? Most of the time I'm on Ubuntu and AFAIK there is no way to use them on Linux, right?

I don't know about that. Note however that this is off topic for this PR. Feel free to create a discussion ticket for this though.

**Comment by Kissaki** [comment]
> Weblate stores/saves `&apos;` instead of `'`. We have to verify this works/shows up fine fine in the client.
> 
> As interpreted xml it should probably work!?

Generally `&apos;` works fine.

We actually had some before too.

[mumble_de.ts:379](https://github.com/mumble-voip/mumble/blob/e2b648103713683d8bbe197ae8c459a6551316c7/src/mumble/mumble_de.ts#L379)

image

[mumble_de.ts:3120](https://github.com/mumble-voip/mumble/blob/e2b648103713683d8bbe197ae8c459a6551316c7/src/mumble/mumble_de.ts#L3120)

**Comment by Kissaki** [comment]
`<translation>` values with two `<numerusform>` elements are preserved; they are still two elements after Weblate/these changes. They are reformatted to a separate line for each `<numerusform>` though.

**Comment by Kissaki** [comment]
Waiting on PR #4829. Weblate is currently locked for translators too because of merge/state conflicts.

**Review by Kissaki — APPROVED** [review]

**Comment by Kissaki** [comment]
A special thank you to Gert-dev, Elias Meyer, and @comradekingu for their especially big change contributions! :)

**Pull request merged**
