### PR TITLE
FEAT(positional-audio): Add support for DT_GNU_HASH, to locate exported symbols

### PR DESCRIPTION
**Pull request by davidebeatrici**
Our Source Engine plugin retrieves the interfaces on Linux through `s_pInterfaceRegs`, an exported symbol.

Left 4 Dead 2 just received a big update and the binaries don't have the `DT_HASH` table anymore.
As a result, the plugin was not finding the symbol anymore.

This is basically a follow-up to #4534, which implemented support for `DT_GNU_HASH` in the overlay code.

### CODE REVIEW

**Review by Krzmbrzl — APPROVED** [review]
I guess a few explanatory comments explaining what is being done exactly would be quite nice in there.

**Comment by Krzmbrzl** [comment]
Given that this is essentially (also) a fix for the L4D2 plugin (at least that's how I understood it), I think we can/should also consider backporting this to 1.4.x. What do you think?

**Comment by davidebeatrici** [comment]
Unfortunately the plugin needs to be updated.

**Comment by Krzmbrzl** [comment]
> I guess a few explanatory comments explaining what is being done exactly would be quite nice in there.

So it seems comments are sold out today?

**Comment by davidebeatrici** [comment]
I think a separate document would be better, because we do the same in the overlay code.

Also, the explanation is probably going to be quite long. For reference: https://flapenguin.me/elf-dt-gnu-hash

**Pull request merged**
